import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeDollarSign, CalendarClock, Car, Check, ChevronDown, ChevronRight, ClipboardCheck, KeyRound, MapPin, Menu, Phone, Route, ShieldCheck, Snowflake, Sun, Truck, Waves, Wrench } from "lucide-react";
import logo from "@/assets/junkmycarreddeer_red-logo.png";
import seasonalPhoto from "@/assets/abandoned-sedan-acreage.jpeg";
import acreagePhoto from "@/assets/old-red-jeep-driveway.jpeg";
import { QuoteForm } from "@/components/quote-form";
import { BreadcrumbSchema, JsonLd } from "@/components/seo-schema";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Cash for Cars Sylvan Lake | Free Towing, Same-Day Pickup",
  description: "Cash for cars in Sylvan Lake, AB. We buy running, junk, scrap and damaged vehicles, tow free from town and lakefront properties, and pay at pickup.",
  alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-sylvan-lake" },
  openGraph: { title: "Cash for Cars Sylvan Lake | Free Towing", description: "Same-day cash offers and free vehicle pickup throughout Sylvan Lake and nearby acreages.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-sylvan-lake", type: "website", images: [{ url: seasonalPhoto.src, width: 1200, height: 630, alt: "Older vehicle ready for free pickup near Sylvan Lake" }] },
};

const phoneDisplay = "(403) 427-0732";
const phoneHref = "tel:+14034270732";
const wearFactors = [
  { icon: Sun, title: "The summer fleet", text: "Cheap second cars used between a cabin and the beach often become permanent yard fixtures when they stop starting. They may be low-value vehicles, but collection is still free and reclaiming the property is usually the point." },
  { icon: Snowflake, title: "Winter storage becomes permanent", text: "Fuel ages, brakes seize, mice find wiring, seals dry and tires flat-spot. By the second or third spring, the vehicle is losing real value every season it remains parked." },
  { icon: Route, title: "The Highway 11 commute", text: "A daily Red Deer commute adds roughly thirteen thousand kilometres a year before recreational driving, plus months of salt and gravel. High kilometres and rocker or brake-line rust are where dealer trade offers fade away." },
] as const;
const offers = [
  ["Old seasonal car or van, non-running, complete", "$200 – $700"],
  ["Non-running with useful parts demand", "$500 – $1,800"],
  ["High-kilometre runner, 10+ years", "$800 – $3,500"],
  ["Hail-damaged, mechanically sound", "$1,000 – $6,000"],
  ["Newer running truck, SUV or car", "$3,000 – $15,000"],
] as const;
const faqs = [
  ["How long does it take you to get here?", "About twenty-two minutes on Highway 11A. Morning calls usually qualify for same-day pickup; afternoon calls are typically next day."],
  ["Do you charge extra to come from Red Deer?", "No. There is no mileage charge, rural surcharge or minimum vehicle value. Towing costs you nothing."],
  ["Can you get a vehicle out of a tight lakefront lot?", "Usually. Describe the approach width, obstructions and ground condition so we can send the right truck."],
  ["The car has not run in four years and the tires are flat.", "That is routine. We bring skates and a winch. Flat tires, seized brakes and missing keys are all normal pickup conditions."],
  ["I am only here in summer. Can you collect while I am away?", "Yes, with arrangements. An authorized person must sign the bill of sale and accept payment, but that person does not have to be you."],
  ["Do you buy boat trailers or RVs?", "Trailers sometimes, depending on condition and registration. RVs and motorhomes depend on size and access. Describe it and we will give you a direct answer."],
] as const;

export default function SylvanLakePage() {
  const schemas = [
    { "@context": "https://schema.org", "@type": "Service", "@id": "https://www.junkmycarreddeer.ca/cash-for-cars-sylvan-lake#service", name: "Cash for Cars in Sylvan Lake", description: "Cash vehicle buying and free pickup throughout Sylvan Lake and surrounding properties.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-sylvan-lake", serviceType: "Cash vehicle buying and free vehicle removal", provider: { "@id": "https://www.junkmycarreddeer.ca/#business" }, areaServed: { "@type": "City", name: "Sylvan Lake", containedInPlace: { "@type": "AdministrativeArea", name: "Alberta" } }, availableChannel: { "@type": "ServiceChannel", servicePhone: { "@type": "ContactPoint", telephone: "+1-403-427-0732", contactType: "sales", areaServed: "CA-AB", availableLanguage: "English" } }, offers: { "@type": "Offer", priceCurrency: "CAD", description: "No-obligation vehicle offer with free towing included" } },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": "https://www.junkmycarreddeer.ca/cash-for-cars-sylvan-lake#faq", url: "https://www.junkmycarreddeer.ca/cash-for-cars-sylvan-lake", mainEntity: faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) },
  ];
  return <>
    <a className="skip-link" href="#main">Skip to main content</a>
    <div className="utility-bar"><div className="shell utility-inner"><span><MapPin aria-hidden="true" /> Sylvan Lake &amp; surrounding acreages</span><span className="utility-promise">25 km from Red Deer · Same-day pickup available</span><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div></div>
    <header className="site-header"><div className="shell header-inner"><Link className="brand" href="/"><Image src={logo} alt="Junk My Car Red Deer" priority sizes="190px" /></Link><nav className="desktop-nav"><a href="#local">Why Sylvan vehicles wear</a><a href="#buy">What we buy</a><a href="#value">What it is worth</a><a href="#coverage">Coverage</a><a href="#questions">FAQ</a></nav><a className="button button-header" href="#sylvan-quote">Get my offer <ArrowRight aria-hidden="true" /></a><details className="menu-button"><summary aria-label="Open navigation"><Menu aria-hidden="true" /></summary><nav><a href="#local">Local vehicle wear</a><a href="#buy">What we buy</a><a href="#value">Vehicle values</a><a href="#coverage">Coverage</a><a href="#questions">FAQ</a></nav></details></div></header>
    <main id="main" className={styles.page}>
      <section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div className={styles.heroCopy}><nav className={styles.breadcrumb}><Link href="/">Home</Link><ChevronRight aria-hidden="true" /><span>Cash for Cars Sylvan Lake</span></nav><p className={styles.kicker}><Waves aria-hidden="true" /> Sylvan Lake, Alberta</p><h1>Cash for Cars in Sylvan Lake <span>— Free Towing, Paid at Pickup</span></h1><p>We are twenty-five minutes down Highway 11A, which means Sylvan Lake pickups happen the same day more often than not. Running, seized, wrecked or rusted through—tell us what you have and we will come with cash and a flat deck.</p><div className={styles.heroActions}><a className="button button-primary" href="#sylvan-quote">Get My Offer <ArrowRight aria-hidden="true" /></a><a href={phoneHref}><Phone aria-hidden="true" /> Call {phoneDisplay}</a></div><div className={styles.heroProof}><span><Check aria-hidden="true" /> Free town &amp; acreage towing</span><span><Check aria-hidden="true" /> Cash or e-transfer at pickup</span></div></div><div className={styles.heroVisual}><Image src={seasonalPhoto} alt="Long-sitting seasonal vehicle near Sylvan Lake" fill priority sizes="(max-width: 900px) 100vw, 46vw" /><div className={styles.heroShade} /><div className={styles.routeCard}><Route aria-hidden="true" /><span><small>Red Deer to Sylvan Lake</small><strong>25 km via Highway 11A</strong></span></div></div></div></section>
      <section id="sylvan-quote" className={styles.quoteSection}><div className={`shell ${styles.quotePanel}`}><QuoteForm /></div></section>

      <section id="local" className={styles.localSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>A different kind of wear</p><h2>A Lake Town Is Unusually Hard on Vehicles</h2><p>Sylvan Lake does not wear out cars the way a normal town does. It wears them out in three distinct ways, and we see all three constantly.</p></div><div className={styles.factorGrid}>{wearFactors.map(({ icon: Icon, title, text }) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section id="buy" className={styles.buySection}><div className={styles.buyImage}><Image src={acreagePhoto} alt="Older vehicle on a Sylvan Lake area property" fill sizes="(max-width: 850px) 100vw, 46vw" /><div><Truck aria-hidden="true" /><span>Running or not.<strong>We bring the equipment.</strong></span></div></div><div className={styles.buyCopy}><p className={styles.kicker}>Almost any vehicle</p><h2>What We Buy Here</h2><article><Car aria-hidden="true" /><div><h3>Vehicle types</h3><p>Sedans, hatchbacks, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesels, minivans, cargo vans, fleet units, farm trucks and old boat tow vehicles.</p></div></article><article><Wrench aria-hidden="true" /><div><h3>Conditions</h3><p>No-starts, seized engines, failed transmissions, hail and collision damage, write-offs, fire or flood damage, frame rust, failed inspections, stripped vehicles and anything that has simply sat too long.</p></div></article><a href="/what-we-buy">See the complete vehicle list <ArrowRight aria-hidden="true" /></a></div></section>

      <section id="value" className={styles.valueSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>Realistic local ranges</p><h2>What It&apos;s Worth</h2></div><div className={styles.valueGrid}><div className={styles.offerTable}><div className={styles.tableHead}><span>Vehicle</span><span>Typical offer</span></div>{offers.map(([vehicle, offer]) => <div key={vehicle}><span>{vehicle}</span><strong>{offer}</strong></div>)}</div><aside><BadgeDollarSign aria-hidden="true" /><h3>What moves the number</h3><p>Trucks and SUVs retain stronger parts demand. Rust—especially in frames and rockers—is the largest value killer. Completeness and an intact catalytic converter matter significantly.</p><p><strong>The number includes towing.</strong> The figure quoted is the figure handed to you, assuming the description is accurate.</p></aside></div></div></section>

      <section id="coverage" className={styles.coverageSection}><div className={`shell ${styles.coverageGrid}`}><div><p className={styles.kicker}>Town, lakefront and rural</p><h2>Where We Collect in Sylvan Lake</h2><div className={styles.areaCards}><article><MapPin aria-hidden="true" /><h3>In town</h3><p>Ryders Ridge, Iron Gate, Beacon Hill, Hewlett Park, Sylvan Meadows, Marina Bay, older streets north of Lakeshore Drive and newer developments toward Highway 20.</p></article><article><Waves aria-hidden="true" /><h3>Lakefront and seasonal</h3><p>Cabins, summer village lots and seasonal properties, including tight approaches and vehicles parked behind trees or on soft ground.</p></article><article><Route aria-hidden="true" /><h3>Acreages</h3><p>Highways 11, 11A and 20, plus the surrounding range roads and long gravel driveways. Rural pickup adds no fee.</p></article></div></div><aside><h3>Nearby communities</h3><p>Free towing also reaches:</p><div><span>Eckville <strong>28 km west</strong></span><span>Bentley <strong>24 km north</strong></span><span>Spruce View <strong>30 km south</strong></span><span>Benalto <strong>Call for timing</strong></span><span>Red Deer <strong>25 km east</strong></span></div><p>Seasonal resident? We can collect while you are away when an authorized person is arranged to sign and accept payment.</p></aside></div></section>

      <section className={styles.processSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>Pickup day</p><h2>Simple Before, During and After</h2></div><div className={styles.processGrid}><article><KeyRound aria-hidden="true" /><h3>Before we arrive</h3><p>Empty the glovebox, console, seats and trunk. Remove your plate. Have photo ID and proof of ownership ready. No cleaning, starting or tire inflation needed.</p></article><article><CalendarClock aria-hidden="true" /><h3>On the day</h3><p>We confirm the description, complete the bill of sale, pay by cash or e-transfer, then load. Most appointments take about twenty minutes.</p></article><article><ClipboardCheck aria-hidden="true" /><h3>After the sale</h3><p>Take your plate and bill of sale to a registry agent, then call your insurer about any refund on an unused prepaid policy.</p></article></div><div className={styles.paperwork}><ShieldCheck aria-hidden="true" /><div><h3>Seasonal, inherited or unusual ownership?</h3><p>A cabin vehicle, estate or missing registration often has a path. Mention the situation when you call so it can be solved before dispatch.</p></div></div></div></section>

      <section id="questions" className={styles.faqSection}><div className={`shell ${styles.faqGrid}`}><div><p className={styles.kicker}>Local questions</p><h2>Sylvan Lake FAQs</h2><p>Answers about timing, access and the types of seasonal vehicles we see around the lake.</p><a href={phoneHref}><Phone aria-hidden="true" /> Ask us directly</a></div><div>{faqs.map(([q, a], index) => <details key={q} open={index === 0}><summary><span>{q}</span><ChevronDown aria-hidden="true" /></summary><p>{a}</p></details>)}</div></div></section>

      <section className={styles.finalSection}><div className={`shell ${styles.finalGrid}`}><div><p className={styles.kicker}>Enough to start</p><h2>Get a Number Today</h2><p>Year, make, model and roughly what is wrong with it.</p></div><div><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a><a href="#sylvan-quote">Get a Free Offer <ArrowRight aria-hidden="true" /></a></div></div></section>
    </main>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><Image src={logo} alt="Junk My Car Red Deer" sizes="230px" /><p>Cash offers and free vehicle towing throughout Sylvan Lake and Central Alberta.</p><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div><div><h3>Services</h3><Link href="/junk-car-removal-red-deer">Junk Car Removal</Link><Link href="/scrap-car-removal-red-deer">Scrap Car Removal</Link><Link href="/sell-my-car-red-deer">Sell My Car</Link><Link href="/free-towing-red-deer">Free Towing</Link></div><div><h3>Company</h3><Link href="/about">About Us</Link><Link href="/how-it-works">How It Works</Link><Link href="/what-we-buy">What We Buy</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></div><div><h3>Visit or contact</h3><p>4909 48 Street<br />Red Deer, AB T4N 1S8</p><a className="footer-quote" href="#sylvan-quote">Request a quote <ArrowRight aria-hidden="true" /></a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Junk My Car Red Deer</span><span>Serving Sylvan Lake &amp; Central Alberta</span></div></footer>
    <div className="mobile-actions"><a href={phoneHref}><Phone aria-hidden="true" /> Call now</a><a href="#sylvan-quote"><BadgeDollarSign aria-hidden="true" /> Get offer</a></div>
    <BreadcrumbSchema current="Cash for Cars Sylvan Lake" path="/cash-for-cars-sylvan-lake" />
    {schemas.map((schema, index) => <JsonLd key={index} data={schema} />)}
  </>;
}
