import type { Metadata } from "next";
import heroPhoto from "@/assets/abandoned-sedan-acreage.jpeg";
import farmPhoto from "@/assets/old-chevrolet-tahoe-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Delburne | Free Farm & Acreage Pickup", description: "Cash for cars in Delburne, Alberta. We come to you — farm trucks, non-runners, scrap and damaged vehicles bought, towed free, paid at pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-delburne" }, openGraph: { title: "Cash for Cars Delburne | We Come to You", description: "Free farm and acreage vehicle pickup throughout Delburne and eastern Red Deer County.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-delburne", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Long-sitting field vehicle near Delburne" }] } };
const data = {
  city: "Delburne", path: "/cash-for-cars-delburne", distance: "38 km", route: "Highway 595",
  heroTitle: "Cash for Cars Delburne — We Come to You", heroText: "Thirty minutes east on Highway 595. There is nowhere local to take a dead vehicle, so we come and get it—any condition, no charge and cash in hand when we load.",
  heroImage: heroPhoto, heroAlt: "Long-sitting vehicle on a Delburne-area property", secondaryImage: farmPhoto, secondaryAlt: "Farm vehicle accepted for free pickup near Delburne",
  localTitle: "Thirty Minutes From Everything", localIntro: "Without a local dealer, wrecker or scrap yard, dead vehicles historically stayed where they stopped. Free collection changes that equation.",
  localFactors: [{ title: "No local option", text: "Towing a vehicle elsewhere costs money and requires a trailer or recovery call, so many were simply parked. We come to the property, charge nothing and pay before loading." }, { title: "Which means things accumulate", text: "One vehicle becomes a row behind the shop. Quoting several together is straightforward and one efficient visit usually improves each offer." }, { title: "Farm country vehicles", text: "Gravel-road half-tons, grain trucks, service units and successive work vehicles are common. Heavy vehicles with useful parts are our best-paying non-runners." }],
  buyTypes: "Cars, SUVs, half-tons, 3/4-tons, one-tons, diesel pickups, grain and farm trucks, vans, work vehicles and fleets.", buyConditions: "No-starts, failed engines or transmissions, hail, collision, write-offs, fire, flood, frame rust, failed inspections, stripped vehicles and units sitting in fields for decades.",
  offers: [["Field car, long-sitting, incomplete", "$150 – $500"], ["Older car, complete, non-running", "$250 – $800"], ["Farm half-ton, non-running", "$600 – $1,800"], ["Grain truck or one-ton", "$900 – $2,800"], ["High-kilometre runner", "$800 – $3,500"], ["Three or more, one property", "Per-vehicle offer improves"]] as const,
  valueText: "Weight creates the baseline and reusable parts plus catalytic converter content add value. Years in a field reduce salvage value through rust and rodents, but even a low-end vehicle has a number and pickup remains free.",
  accessTitle: "Where We Collect", accessIntro: "Delburne and the farms, acreages and rural properties across eastern Red Deer County are fully covered.", accessItems: [{ title: "Village and county", text: "Highways 595, 21 and 42, the Pine Lake area and all connecting range roads." }, { title: "Fields and shelterbelts", text: "Long approaches, quonsets, treelines and vehicles well away from the road are routine." }, { title: "Ground conditions", text: "We travel as far as firm ground permits and return later rather than rut cultivated land or a yard." }],
  process: "Call or submit what you know. If several vehicles are difficult to identify, describe them generally and we can assess the group. Offers return the same day and pickup is usually same day or next.", paperwork: "We complete the bill of sale. Long-sitting units frequently have lost documents, an unrecorded transfer or a deceased registered owner. Most have a path, but call before dispatch so requirements are clear.",
  nearby: [["Elnora", "22 km southeast"], ["Alix", "30 km north"], ["Red Deer", "38 km west"], ["Stettler", "48 km east"], ["Pine Lake", "Area included"]] as const,
  faqs: [["Do I have to get it to you?", "No. We come to the vehicle wherever it sits at no charge."], ["It has been in a field for fifteen years.", "Very normal. Expect a modest but real offer; removal remains free."], ["There are five and I cannot identify half of them.", "Describe what you can and we can assess the group."], ["The registration is in my late father's name.", "Common. Call with the documents you have and we will explain what is required."], ["How far off pavement will you go?", "As far as the ground carries the truck. Describe access when calling."], ["Is there a minimum value?", "No minimum, trip charge or towing fee."]] as const,
  finalTitle: "Get a Number",
};
export default function Page(){return <LocationPage data={data}/>;}
