import type { Metadata } from "next";
import heroPhoto from "@/assets/old-chevrolet-tahoe-acreage.jpeg";
import servicePhoto from "@/assets/older-ford-f150-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Stettler AB | Free Towing & Same-Day Cash", description: "Cash for cars Stettler, Alberta. We buy running, junk, scrap, oilfield and damaged vehicles, tow free the full 80 km, and pay you at pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-stettler" }, openGraph: { title: "Cash for Cars Stettler | Full 80 km Tow Free", description: "Cash paid for oilfield, farm, lake and everyday vehicles across Stettler and the county.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-stettler", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Vehicle ready for free pickup near Stettler" }] } };
const data = {
  city: "Stettler", path: "/cash-for-cars-stettler", distance: "80 km", route: "Highway 12",
  heroTitle: "Cash for Cars Stettler — The Full Tow Is Free", heroText: "Stettler is the farthest town we serve and the tow is still free. Any vehicle, any condition—one number over the phone and cash in your hand when we load it.",
  heroImage: heroPhoto, heroAlt: "Long-sitting vehicle on a Stettler County property", secondaryImage: servicePhoto, secondaryAlt: "Older service truck accepted for cash near Stettler",
  localTitle: "Out Here, Nobody Comes", localIntro: "The vehicle is not worth less in Stettler. The problem is finding a buyer who will make the trip without subtracting the distance afterward.",
  localFactors: [{ title: "The distance problem", text: "We build the eighty-kilometre run into our quote rather than deducting it. One vehicle is enough to justify the trip, whether on Main Street or beyond Erskine." }, { title: "An oil and gas service town", text: "Service-body 3/4-tons, one-tons, welding trucks and retired crew cabs are heavy, parts-rich vehicles with drivetrain demand across Alberta." }, { title: "Buffalo Lake summer properties", text: "Cheap second cars at Buffalo Lake, Rochon Sands and summer villages eventually stop starting. They may be modest-value vehicles, but removal remains free and can be arranged for seasonal owners." }],
  buyTypes: "Half-tons, 3/4-tons, one-tons, duallies, diesel and service trucks, welding rigs, cars, SUVs, vans, grain and farm trucks, commercial units and fleets.", buyConditions: "No-starts, seized engines, failed transmissions, hail, collision, write-offs, fire, flood, frame rust, failed inspections and partly stripped vehicles.",
  offers: [["Seasonal lake car, non-running", "$200 – $700"], ["Older car, complete, non-running", "$250 – $800"], ["Half-ton, non-running, complete", "$600 – $1,800"], ["Service truck or one-ton, non-running", "$900 – $3,000"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck, SUV or car", "$3,000 – $15,000"], ["Three or more, one location", "Per-vehicle offer improves"]] as const,
  valueText: "Steel service bodies add hundreds of kilos over a standard box, creating a strong weight floor. Reusable components and catalytic converters add value above that. Frame rust and missing parts are the main deductions.",
  servicesIntro: "At eighty kilometres, Stettler is the edge of our map—and every service below still includes the full tow, with nothing deducted for distance and payment before the vehicle is loaded.",
  services: [
    { title: "Junk Car Removal in Stettler", before: "The vehicle behind the shop that has stayed there because no buyer would make the drive is exactly what our ", linkLabel: "junk car removal service", href: "/junk-car-removal-red-deer", after: " is for out here. One vehicle is worth the trip—you do not need to wait until three have piled up." },
    { title: "Scrap Car Removal in Stettler", before: "Units left sitting in a County of Stettler field since the nineties, or picked clean for parts, are usually scrap. Our ", linkLabel: "scrap car removal", href: "/scrap-car-removal-red-deer", after: " collects them from yards around Erskine, Botha and Donalda and processes them properly—fluids captured, metal recycled, nothing left leaking into pasture." },
    { title: "Sell My Car in Stettler", before: "Few private buyers will drive to Stettler to look at a used car, which leaves running vehicles here with nowhere to go. Our ", linkLabel: "sell my car service", href: "/sell-my-car-red-deer", after: " gives you one cash offer that already includes the eighty-kilometre tow—no ads, no waiting for someone from Red Deer to show up." },
    { title: "Damaged and Write-Off Vehicles in Stettler", before: "Hail and wildlife strikes on Highways 12 and 56 write off plenty of vehicles that still run perfectly well underneath. Our ", linkLabel: "damaged car buying service", href: "/damaged-car-removal-red-deer", after: " buys salvage and non-repairable buybacks and prices the working drivetrain and parts, not just the dents." },
    { title: "Car Wreckers Serving Stettler", before: "Retired service trucks, welding rigs and crew cabs from the local energy sector are some of the most parts-rich vehicles we buy. As ", linkLabel: "car wreckers", href: "/car-wreckers-red-deer", after: " we dismantle and recover their drivetrain and steel service bodies—and if the welder or equipment still works, we will tell you whether it is worth selling separately." },
    { title: "Free Towing in Stettler", before: "Fifty-five minutes on Highway 12, then down to a Buffalo Lake cabin or a Rochon Sands lot—still free. ", linkLabel: "Free towing", href: "/free-towing-red-deer", after: " covers the whole County of Stettler, including seasonal properties where someone authorised signs on your behalf." },
  ],
  accessTitle: "Where We Collect", accessIntro: "The full town, county, Buffalo Lake area and range-road network are inside the free pickup area.", accessItems: [{ title: "In Stettler", text: "Residential streets, Main Street and 50 Avenue, commercial yards, light industrial properties, shops and company yards." }, { title: "County and lake", text: "Erskine, Red Willow, Botha, Nevis, Donalda, Buffalo Lake and Rochon Sands, plus Highways 12, 56 and 590." }, { title: "Long approaches", text: "Gravel and field access are routine. We reschedule for genuinely soft ground rather than rut a rural approach." }],
  process: "Send the year, make, model and honest description. The same-day offer includes the complete tow. Pickups are usually next day and come with a defined time window.", paperwork: "We complete the bill of sale. Company service vehicles, estates and units owned by closed businesses are workable with the proper signing authority and documents arranged before dispatch.",
  nearby: [["Alix", "40 km west"], ["Clive", "45 km west"], ["Elnora", "40 km southwest"], ["Delburne", "48 km west"], ["County of Stettler", "All rural properties"]] as const,
  faqs: [["Do you really come all the way out here for free?", "Yes. Eighty kilometres with no mileage charge, pickup deduction or minimum value."], ["Is one car worth the trip?", "Yes. Routing is our responsibility; you do not need several vehicles."], ["Do you buy welding trucks and service bodies?", "Regularly. Their weight and parts content often place them near the top of non-running offers."], ["The company that owned it is closed.", "Often workable with the correct documentation. Call and we will explain what is needed."], ["Can you pick up from a Buffalo Lake property?", "Yes. An authorized person must sign and accept payment, but arrangements can be made for seasonal owners."], ["How long does it take you to get here?", "About fifty-five minutes on Highway 12. Pickup is normally next day."], ["It has sat in a field since the nineties.", "Fine. Seized brakes, flat tires, rodents and vegetation are normal."]] as const,
  finalTitle: "Get a Number Today",
};
export default function Page(){return <LocationPage data={data}/>;}
