import type { Metadata } from "next";
import heroPhoto from "@/assets/older-ford-f150-acreage.jpeg";
import westPhoto from "@/assets/old-chevrolet-tahoe-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Spruce View | Free Acreage Car Removal", description: "Cash for cars Spruce View, Alberta. We buy tow vehicles, ranch trucks, non-runners, scrap and damaged vehicles, tow free, and pay you at pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-spruce-view" }, openGraph: { title: "Cash for Cars Spruce View | West Country Pickup", description: "Free pickup for tow rigs, ranch trucks and unwanted vehicles throughout Spruce View and Gleniffer Lake.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-spruce-view", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Tow rig ready for cash pickup near Spruce View" }] } };
const data = {
  city: "Spruce View", path: "/cash-for-cars-spruce-view", distance: "45 km", route: "Highway 54",
  heroTitle: "Cash for Cars Spruce View — West Country Pickup", heroText: "Thirty-eight minutes southwest on Highway 54. Tow rigs, ranch trucks, cars and write-offs—one number with towing included, paid wherever you are.",
  heroImage: heroPhoto, heroAlt: "Tow vehicle on a Spruce View acreage", secondaryImage: westPhoto, secondaryAlt: "Rural vehicle accepted near Gleniffer Lake",
  localTitle: "Trucks Here Spend Their Lives Pulling", localIntro: "West Country recreation, gravel roads and acreage space produce tow rigs with heavy mechanical wear and properties where retired vehicles accumulate.",
  localFactors: [{ title: "The recreation corridor", text: "Holiday trailers, boats, quads, sleds, stock trailers and firewood loads work transmissions, rear ends, brakes and suspension harder than the odometer shows. Weight and parts still retain value." }, { title: "Gravel is the default", text: "Chipped glass, steering and suspension wear, dust and underbody damage are normal local conditions and affect our offer far less than a private sale." }, { title: "Ranch and acreage accumulation", text: "A retired truck, winter no-start and old work vehicle can remain because there is room. Collecting several together improves efficiency and typically the offer." }],
  buyTypes: "Half-tons, 3/4-tons, one-tons, diesel pickups, ranch and work trucks, SUVs, crossovers, cars, vans, commercial and fleet units.", buyConditions: "No-starts, failed engines, transmissions or rear ends, hail, collision, write-offs, fire, flood, rusted frames, failed inspections and stripped vehicles.",
  offers: [["Older car, complete, non-running", "$250 – $800"], ["Tow-rig half-ton, tired drivetrain", "$600 – $1,800"], ["3/4-ton, one-ton or diesel, non-running", "$900 – $3,000"], ["High-kilometre runner", "$800 – $3,500"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Three or more, one property", "Per-vehicle offer improves"]] as const,
  valueText: "Tow rigs tend to be heavy, creating a stronger material floor. Reusable parts and catalytic converter content add value; severe rust and missing components reduce it. The number includes rural towing and stands on arrival.",
  servicesIntro: "Tow rigs, ranch trucks and the vehicles that settle onto West Country acreages—each service below covers Spruce View, Gleniffer Lake and surrounding Red Deer County, with free towing and payment on collection.",
  services: [
    { title: "Junk Car Removal in Spruce View", before: "The car that stopped running one winter and has sat in the treeline since is a regular Spruce View pickup. Our ", linkLabel: "junk car removal service", href: "/junk-car-removal-red-deer", after: " winches it out from behind the shop or across soft acreage ground—keys, battery and tires optional." },
    { title: "Scrap Car Removal in Spruce View", before: "A truck kept for parts on a ranch west of the hamlet eventually has nothing useful left but steel. Our ", linkLabel: "scrap car removal", href: "/scrap-car-removal-red-deer", after: " pays on weight and metal and drains fluids properly—which matters on land that drains toward the Red Deer River and Gleniffer Lake." },
    { title: "Sell My Car in Spruce View", before: "A half-ton that has pulled holiday trailers and sled decks for years still runs—but buyers who hear “towing” start lowballing. Our ", linkLabel: "sell my car service", href: "/sell-my-car-red-deer", after: " prices it on weight and parts instead, so a tired drivetrain costs you far less." },
    { title: "Damaged and Write-Off Vehicles in Spruce View", before: "Wildlife on Highway 54 and the gravel roads toward Dickson, plus summer hail, write off a steady number of vehicles here. Our ", linkLabel: "damaged car buying service", href: "/damaged-car-removal-red-deer", after: " buys salvage and non-repairable buybacks and prices the healthy parts behind the impact." },
    { title: "Car Wreckers Serving Spruce View", before: "Tow rigs are heavy and packed with components that sell—hitches, axles, transfer cases and 4x4 hardware. As ", linkLabel: "car wreckers", href: "/car-wreckers-red-deer", after: " we recover those parts, which is why a truck with a finished transmission still earns a solid number." },
    { title: "Free Towing in Spruce View", before: "Thirty-eight minutes down Highway 54 and out to a Gleniffer Lake lot or a ranch off Highway 781—no charge. ", linkLabel: "Free towing", href: "/free-towing-red-deer", after: " covers the hamlet, resort properties and surrounding acreages, with access to resort lots arranged a day ahead." },
  ],
  accessTitle: "Where We Collect", accessIntro: "Spruce View, Gleniffer Lake, Dickson and surrounding Red Deer County acreages are all covered.", accessItems: [{ title: "Hamlet and county", text: "Highways 54, 761 and 781 and the connecting range-road network." }, { title: "Gleniffer Lake and Dickson", text: "Resort and seasonal properties are included. Some managed properties need advance notice for truck access." }, { title: "Ranch and field access", text: "Long gravel approaches, shops, treelines and fields are routine when the ground supports a loaded truck." }],
  process: "Call or send the year, make, model and honest condition. Offers return the same day and pickup is normally the same day or next.", paperwork: "We prepare the bill of sale. Company work trucks, farm-corporation units and estates are workable when signing authority and documentation are confirmed before pickup.",
  nearby: [["Innisfail", "25 km east"], ["Eckville", "30 km north"], ["Sylvan Lake", "35 km north"], ["Olds", "40 km southeast"], ["Gleniffer Lake", "Properties included"]] as const,
  faqs: [["The transmission is finished from towing.", "That is a common purchase. The truck remains heavy and parts-rich, protecting much of its value."], ["Do you collect from Gleniffer Lake properties?", "Yes. Arrange any resort access notice a day ahead."], ["Is there a charge for coming this far?", "No mileage fee, minimum value or pickup deduction."], ["Do you buy trailers or campers?", "Sometimes, depending on condition and registration. Describe it for a direct answer."], ["How far off pavement will you go?", "As far as firm ground allows. Describe the approach when calling."], ["Several vehicles on one property?", "One efficient trip generally improves the per-vehicle offer."]] as const,
  finalTitle: "Get a Number",
};
export default function Page(){return <LocationPage data={data}/>;}
