import type { Metadata } from "next";
import heroPhoto from "@/assets/old-red-jeep-driveway.jpeg";
import bushPhoto from "@/assets/old-chevrolet-tahoe-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Eckville | Free Towing, Cash on the Spot", description: "Cash for cars Eckville, Alberta. We buy non-running, high-mileage, scrap and damaged vehicles, tow free from town and acreages, and pay when we collect.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-eckville" }, openGraph: { title: "Cash for Cars Eckville | David Thompson Corridor", description: "Free towing and cash offers for cars and hard-working trucks throughout Eckville and western Lacombe County.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-eckville", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Hard-working vehicle ready for pickup near Eckville" }] } };
const data = {
  city: "Eckville", path: "/cash-for-cars-eckville", distance: "52 km", route: "Highway 11",
  heroTitle: "Cash for Cars Eckville — Free Corridor Towing", heroText: "Forty-two minutes west on Highway 11. Running, seized, wrecked or rusted—we will buy it, tow it free and hand you cash before it goes on the deck.",
  heroImage: heroPhoto, heroAlt: "Older vehicle ready for cash pickup near Eckville", secondaryImage: bushPhoto, secondaryAlt: "Bush and acreage vehicle accepted near Eckville",
  localTitle: "Vehicles Here Work Harder Than Most", localIntro: "Highway 11 travel, west-country recreation and acreage space create high-kilometre trucks with a different kind of wear.",
  localFactors: [{ title: "The Highway 11 life", text: "Long highway distances, winter weather and gravel toward Rocky Mountain House, Nordegg and work camps produce kilometres, chipped glass, suspension wear and undercarriage damage that hurt trade-in value far more than ours." }, { title: "Bush trucks and quad haulers", text: "Trucks that hauled quads, sleds, firewood and trailers may be mechanically tired but remain heavy and rich in reusable components." }, { title: "Acreages that collect vehicles", text: "Space lets old vehicles stay behind shops for years. We often clear several at once, improving the per-vehicle offer through an efficient trip." }],
  buyTypes: "Cars, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesel pickups, farm and work trucks, vans, commercial units and fleets.", buyConditions: "No-starts, failed engines or transmissions, hail, collision, write-offs, fire, flood, rusted frames, failed inspections and partly stripped vehicles.",
  offers: [["Older car, complete, non-running", "$250 – $800"], ["Half-ton, non-running, complete", "$600 – $1,800"], ["3/4-ton or diesel, non-running", "$900 – $3,000"], ["High-kilometre runner", "$800 – $3,500"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck, SUV or car", "$3,000 – $15,000"]] as const,
  valueText: "Weight sets the baseline, salvageable components and catalytic converter content create the upside, and rust lowers it. A vehicle already picked over is worth less, so describe missing parts accurately. Towing from Red Deer is included.",
  servicesIntro: "Bush trucks, Highway 11 commuters and the vehicles that have sat behind the shop since 2014—each service below covers Eckville and western Lacombe County, with free towing and cash before the vehicle leaves.",
  services: [
    { title: "Junk Car Removal in Eckville", before: "The vehicle parked behind the shop years ago and never moved again is the most common Eckville call we get. Our ", linkLabel: "junk car removal service", href: "/junk-car-removal-red-deer", after: " gets it out whatever state it is in—seized brakes, flat tires, rodent-chewed wiring—and clears several from one acreage in a single visit." },
    { title: "Scrap Car Removal in Eckville", before: "Vehicles left for years on Medicine River properties are often rusted and incomplete, with old fluids still inside. Our ", linkLabel: "scrap car removal", href: "/scrap-car-removal-red-deer", after: " pays on weight and recoverable metal and drains everything properly before processing, so nothing seeps toward the river." },
    { title: "Sell My Car in Eckville", before: "High kilometres, chipped glass and a worn suspension from years on the David Thompson corridor gut a trade-in. Our ", linkLabel: "sell my car service", href: "/sell-my-car-red-deer", after: " prices a running vehicle on weight, parts and material instead—one cash offer, with no local buyer to haggle against." },
    { title: "Damaged and Write-Off Vehicles in Eckville", before: "Deer and elk on Highway 11 and the west-country roads write off a lot of vehicles here, especially at dusk. Our ", linkLabel: "damaged car buying service", href: "/damaged-car-removal-red-deer", after: " buys wildlife-strike, collision and hail write-offs, salvage and non-repairable included, and prices what is healthy behind the damage." },
    { title: "Car Wreckers Serving Eckville", before: "Trucks that have hauled quads, sleds and firewood for years still carry hitches, axles, transfer cases and 4x4 components that sell. As ", linkLabel: "car wreckers", href: "/car-wreckers-red-deer", after: " we recover those parts, which is why a worn-out bush truck is among the better-paying non-runners we buy." },
    { title: "Free Towing in Eckville", before: "Forty-two minutes west on Highway 11, then down a gravel approach off Highway 766 or 761—still free. ", linkLabel: "Free towing", href: "/free-towing-red-deer", after: " covers town, Medicine River acreages and bush-access properties, as long as the ground will carry the truck." },
  ],
  accessTitle: "Where We Collect", accessIntro: "All of Eckville and the surrounding western Lacombe County corridor are covered without a trip charge.", accessItems: [{ title: "Town and county", text: "Properties along Highways 11, 766 and 761 plus the surrounding range roads." }, { title: "Medicine River and bush access", text: "Long gravel approaches, rural properties and vehicles beyond pavement are routine when access supports the truck." }, { title: "Ground conditions", text: "If reaching the vehicle would rut an approach or yard, we return when it firms rather than damage the property." }],
  process: "Call or use the form with the year, make, model and condition. We return a same-day offer; pickup is usually the same day or next.", paperwork: "We complete the bill of sale. Company, estate and never-transferred vehicles often have a solution, but ownership should be discussed before pickup day.",
  nearby: [["Sylvan Lake", "28 km east"], ["Bentley", "22 km north"], ["Spruce View", "30 km south"], ["Rimbey", "35 km north"], ["Lacombe County", "Rural pickup included"]] as const,
  faqs: [["Is there a charge to come from Red Deer?", "No mileage fee, minimum value or deduction at pickup."], ["The truck has been used hard on bush roads.", "Expected. Suspension and undercarriage wear affect us much less because we value weight and parts."], ["Do you go beyond the pavement?", "Yes, when the ground carries the truck. Describe access when calling."], ["There are three vehicles on my property.", "We can clear them together, which generally improves each offer."], ["It has not run in ten years.", "Routine. Seized brakes, flat tires and rodent damage are normal."], ["How fast can you get here?", "About forty-two minutes on Highway 11. Morning calls often qualify for same-day pickup."]] as const,
  finalTitle: "Get a Number",
};
export default function Page(){return <LocationPage data={data}/>;}
