import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { BreadcrumbSchema, JsonLd } from "@/components/seo-schema";
import { ArrowRight, Camera, Car, Check, ChevronRight, Clock3, Mail, MapPin, Menu, Phone, Route, ShieldCheck } from "lucide-react";
import logo from "@/assets/junkmycarreddeer_red-logo.png";
import mapImage from "@/assets/red-deer-city-map.png";
import { QuoteForm } from "@/components/quote-form";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Contact Us | Cash for Cars Red Deer",
  description: "Call or message us for a same-day cash offer on any vehicle in Red Deer and Central Alberta. Free towing included, no obligation.",
  alternates: { canonical: "https://www.junkmycarreddeer.ca/contact" },
  openGraph: { title: "Contact Junk My Car Red Deer", description: "Request a same-day vehicle offer with free towing across Red Deer and Central Alberta.", url: "https://www.junkmycarreddeer.ca/contact", type: "website", images: [{ url: mapImage.src, width: 1200, height: 630, alt: "Red Deer and Central Alberta service area" }] },
};

const phoneDisplay = "(403) 427-0732";
const phoneHref = "tel:+14034270732";
const email = "offers@junkmycarreddeer.ca";
const towns = ["Springbrook", "Penhold", "Blackfalds", "Sylvan Lake", "Lacombe", "Innisfail", "Delburne", "Bentley", "Clive", "Spruce View", "Bowden", "Eckville", "Alix", "Ponoka", "Elnora", "Rimbey", "Olds", "Stettler"];

export default function ContactPage() {
  const localBusinessSchema = { "@context": "https://schema.org", "@type": "AutomotiveBusiness", "@id": "https://www.junkmycarreddeer.ca/#business", name: "Junk My Car Red Deer", url: "https://www.junkmycarreddeer.ca/", logo: "https://www.junkmycarreddeer.ca/junk-my-car-red-deer-logo.png", telephone: "+1-403-427-0732", email, address: { "@type": "PostalAddress", streetAddress: "4909 48 Street", addressLocality: "Red Deer", addressRegion: "AB", postalCode: "T4N 1S8", addressCountry: "CA" }, areaServed: "Red Deer and Central Alberta" };
  return <>
    <a className="skip-link" href="#main">Skip to main content</a>
    <div className="utility-bar"><div className="shell utility-inner"><span><MapPin aria-hidden="true" /> Red Deer &amp; 80 km around</span><span className="utility-promise">Same-day replies · Free quotes · Free towing</span><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div></div>
    <header className="site-header"><div className="shell header-inner"><Link className="brand" href="/"><Image src={logo} alt="Junk My Car Red Deer" priority sizes="190px" /></Link><nav className="desktop-nav" aria-label="Contact page navigation"><a href="#details">Contact details</a><a href="#cash-offer">Get an offer</a><a href="#prepare">Before you call</a><a href="#coverage">Coverage</a><Link href="/faq">FAQ</Link></nav><a className="button button-header" href="#cash-offer">Get a cash offer <ArrowRight aria-hidden="true" /></a><details className="menu-button"><summary aria-label="Open navigation"><Menu aria-hidden="true" /></summary><nav><a href="#details">Contact details</a><a href="#cash-offer">Get an offer</a><a href="#prepare">Before you call</a><a href="#coverage">Coverage</a></nav></details></div></header>
    <main id="main" className={styles.page}>
      <section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div><nav className={styles.breadcrumb}><Link href="/">Home</Link><ChevronRight aria-hidden="true" /><span>Contact</span></nav><p className={styles.kicker}>A real person, the same day</p><h1>Contact <span>Us</span></h1><p>Fastest way to get a number is to phone. If it is outside hours or you would rather write it out, use the form and we will come back to you the same day.</p><div className={styles.heroActions}><a href={phoneHref} className="button button-primary"><Phone aria-hidden="true" /> Call {phoneDisplay}</a><a href="#cash-offer">Send vehicle details <ArrowRight aria-hidden="true" /></a></div></div><div className={styles.heroCard}><span>Response time</span><strong>Usually within a few hours.</strong><p>Year, make, model and what is wrong—that is enough to begin.</p><div><Check aria-hidden="true" /> No obligation</div><div><Check aria-hidden="true" /> No towing fee</div><div><Check aria-hidden="true" /> No pressure</div></div></div></section>

      <section id="details" className={styles.detailsSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>Get in touch</p><h2>Call, Write or Visit</h2></div><div className={styles.detailGrid}><a href={phoneHref}><Phone aria-hidden="true" /><span>Call or text</span><strong>{phoneDisplay}</strong><small>Tap to call on mobile</small></a><a href={`mailto:${email}`}><Mail aria-hidden="true" /><span>Email</span><strong>{email}</strong><small>Send details or photos</small></a><div><MapPin aria-hidden="true" /><span>Address</span><strong>4909 48 Street</strong><small>Red Deer, AB T4N 1S8</small></div><div><Clock3 aria-hidden="true" /><span>Hours</span><strong>Mon–Sat: 8am–8pm</strong><small>Sunday: By appointment</small></div></div><div className={styles.map}><iframe title="Junk My Car Red Deer location map" src="https://www.google.com/maps?q=4909%2048%20Street%2C%20Red%20Deer%2C%20AB%20T4N%201S8&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div><MapPin aria-hidden="true" /><p><strong>Junk My Car Red Deer</strong><br />4909 48 Street, Red Deer</p><a href="https://www.google.com/maps/search/?api=1&query=4909%2048%20Street%20Red%20Deer%20AB%20T4N%201S8" target="_blank" rel="noreferrer">Open directions <ArrowRight aria-hidden="true" /></a></div></div></div></section>

      <section id="cash-offer" className={styles.formSection}><div className={`shell ${styles.formGrid}`}><div className={styles.formIntro}><p className={styles.kicker}>No-obligation valuation</p><h2>Get a Cash Offer</h2><p>Give us enough to identify and locate the vehicle. Photos are helpful for unusual damage or difficult access, but they are not required to receive a quote.</p><div><ShieldCheck aria-hidden="true" /><span><strong>Your details stay private.</strong> We only use them to quote and complete your vehicle sale.</span></div></div><QuoteForm /></div></section>

      <section id="prepare" className={styles.prepareSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>A two-minute call</p><h2>What to Have Ready</h2><p>None of this is required, but having it nearby keeps the call short and the quote accurate.</p></div><div className={styles.prepareGrid}><article><div><Car aria-hidden="true" /></div><span>About the vehicle</span><h3>What it is and what happened</h3><ul><li>Year, make and model</li><li>Whether it runs and roughly what is wrong</li><li>Anything missing, including converter, wheels or drivetrain</li><li>Approximate mileage, if known</li></ul></article><article><div><Route aria-hidden="true" /></div><span>About where it is</span><h3>Location and access</h3><ul><li>Address, nearest town or rural directions</li><li>Garage, field, alley, parkade or compound</li><li>Snow, fencing, another vehicle or soft ground</li><li>Any deadline affecting collection</li></ul></article><aside><Camera aria-hidden="true" /><h3>A photo saves a long description.</h3><p>Text a couple of pictures to {phoneDisplay}, especially for tight access, collision damage or missing parts.</p><a href={`sms:+14034270732`}>Text photos <ArrowRight aria-hidden="true" /></a></aside></div></div></section>

      <section id="coverage" className={styles.coverageSection}><div className={styles.coverageImage}><Image src={mapImage} alt="Map of the Red Deer and Central Alberta pickup area" fill sizes="(max-width: 900px) 100vw, 46vw" /></div><div className={styles.coverageCopy}><p className={styles.kicker}>We come to you</p><h2>Red Deer and Central Alberta</h2><p>Every Red Deer neighbourhood, residential and industrial, plus acreages and country residential throughout Red Deer County. Towing is free across all eighteen surrounding communities.</p><div>{towns.map((town) => <span key={town}>{town}</span>)}</div><p><strong>Not listed but nearby?</strong> Call anyway. There is a good chance we can make the trip.</p></div></section>

      <section className={styles.knowSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>Before you call</p><h2>Three Things Worth Knowing</h2></div><div className={styles.knowGrid}><article><Check aria-hidden="true" /><h3>There is no cost</h3><p>The quote and towing are free. There is no obligation and nothing is deducted at pickup.</p></article><article><Check aria-hidden="true" /><h3>Paperwork can come later</h3><p>You need ID and proof of ownership at pickup, not to learn the vehicle’s value. Tell us if ownership is complicated.</p></article><article><Check aria-hidden="true" /><h3>We call back</h3><p>If you reach voicemail, leave the year, make and model. You will hear from us the same day.</p></article></div><div className={styles.finalCta}><div><h2>Ready When You Are</h2><p>Call now or send the vehicle details. Either way, you will speak with a real person.</p></div><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a><a href="#cash-offer">Get a Free Offer <ArrowRight aria-hidden="true" /></a></div></div></section>
    </main>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><Image src={logo} alt="Junk My Car Red Deer" sizes="230px" /><p>Fair cash offers, free towing and same-day pickup across Central Alberta.</p><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div><div><h3>Services</h3><Link href="/junk-car-removal-red-deer">Junk Car Removal</Link><Link href="/scrap-car-removal-red-deer">Scrap Car Removal</Link><Link href="/free-towing-red-deer">Free Towing</Link></div><div><h3>Company</h3><Link href="/about">About Us</Link><Link href="/how-it-works">How It Works</Link><Link href="/what-we-buy">What We Buy</Link><Link href="/faq">FAQ</Link></div><div><h3>Visit or contact</h3><p>4909 48 Street<br />Red Deer, AB T4N 1S8</p><a className="footer-quote" href="#cash-offer">Request a quote <ArrowRight aria-hidden="true" /></a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Junk My Car Red Deer</span><span>Serving Red Deer &amp; Central Alberta</span></div></footer>
    <BreadcrumbSchema current="Contact Us" path="/contact" />
    <JsonLd data={localBusinessSchema} />
  </>;
}
