import type { Metadata } from "next";
import heroPhoto from "@/assets/used-sedan-red-deer.jpeg";
import garagePhoto from "@/assets/old-red-jeep-driveway.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Alix AB | Free Pickup & Same-Day Cash", description: "Cash for cars in Alix, Alberta. We buy long-owned, non-running, estate, scrap and damaged vehicles, tow free from the village and county, and pay on pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-alix" }, openGraph: { title: "Cash for Cars Alix | Estate and Garage Vehicles", description: "Free pickup and same-day offers for long-owned, estate and farm vehicles throughout Alix.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-alix", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Garage-kept used vehicle purchased in Alix" }] } };
const data = {
  city: "Alix", path: "/cash-for-cars-alix", distance: "52 km", route: "Highway 12",
  heroTitle: "Cash for Cars Alix — Paid the Same Day", heroText: "Forty minutes from Red Deer on Highway 12. Whether it is a car untouched for years, an estate to settle or a garage to clear, we handle it simply and pay fairly.",
  heroImage: heroPhoto, heroAlt: "Long-owned vehicle ready for cash pickup in Alix", secondaryImage: garagePhoto, secondaryAlt: "Garage and driveway vehicle removal near Alix",
  localTitle: "The Car That Outlasted the Driving", localIntro: "Long ownership, life changes and estate clear-outs produce complete, often garage-kept vehicles that are better than their years of inactivity suggest.",
  localFactors: [{ title: "A settled village", text: "Cars bought new and kept for decades may remain in a garage after someone stops driving. Low kilometres, shelter and completeness often make them stronger purchases than owners expect." }, { title: "Estates and clearing a house", text: "Families often travel from another city with limited time. We can make the vehicle the easy part, provided authority-to-sell documents are confirmed before the trip." }, { title: "Farm land around the village", text: "Older trucks accumulate on nearby Lacombe County farms. Several cleared in one visit normally produce a better per-vehicle offer." }],
  buyTypes: "Cars, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesel pickups, farm and work trucks, vans, commercial and fleet vehicles.", buyConditions: "No-starts, dead batteries after years parked, failed engines or transmissions, hail, collision, write-offs, rusted frames, failed inspections and partly stripped vehicles.",
  offers: [["Low-kilometre garage-kept car, non-running", "$500 – $2,500"], ["Older car, complete, non-running", "$250 – $800"], ["Farm or work truck, non-running", "$600 – $2,000"], ["High-kilometre runner", "$800 – $3,500"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running car, SUV or truck", "$3,000 – $15,000"]] as const,
  valueText: "Garage storage and low kilometres help through reduced rust, complete interiors and better reusable parts. Weight provides the baseline, while salvageable components and catalytic converter content create the upside. Towing is included.",
  accessTitle: "Where We Collect", accessIntro: "Every Alix address and the surrounding Lacombe County farms and acreages are inside the free pickup area.", accessItems: [{ title: "Village garages", text: "Garages, driveways and back lanes throughout Alix. A photo of a tight older single stall helps us plan the winch line." }, { title: "Lake and creek areas", text: "Highways 12, 21 and 601, Alix Lake, Parlby Creek and nearby rural roads." }, { title: "County farms", text: "Long approaches, yards and multi-vehicle properties are routine when ground conditions support the truck." }],
  process: "Call or submit the year, make, model and condition. Offers return the same day and pickup is normally same day or next. Check long-parked cars carefully for documents, keys and keepsakes before collection.", paperwork: "We complete the bill of sale. Estate vehicles require documentation showing authority to sell. Call before travelling so the sale can be completed in one visit.",
  nearby: [["Clive", "13 km west"], ["Lacombe", "32 km west"], ["Delburne", "30 km south"], ["Stettler", "40 km east"], ["Lacombe County", "Rural pickup included"]] as const,
  faqs: [["The car has not moved in five years but is in good shape.", "Garage-kept, complete and low-kilometre vehicles are often among our stronger purchases."], ["I am settling my mother's estate from another province.", "Call before travelling and we will explain exactly which documents are required."], ["It is in a narrow old garage.", "Manageable. Send a photo so we bring the right equipment."], ["Is there a charge to come out?", "No mileage fee, minimum value or pickup deduction."], ["Do you buy farm trucks too?", "Yes, one at a time or several together."], ["How long before you can get here?", "About forty minutes. Same-day service is often possible for morning calls."]] as const,
  finalTitle: "Get a Quote",
};
export default function Page(){return <LocationPage data={data}/>;}
