import type { Metadata } from "next";
import heroPhoto from "@/assets/abandoned-sedan-acreage.jpeg";
import yardPhoto from "@/assets/old-chevrolet-suburban-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Elnora AB | Free Rural Vehicle Pickup", description: "Cash for cars in Elnora, Alberta. We buy grain trucks, long-sitting farmyard vehicles, non-runners and write-offs, tow free, and pay you at pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-elnora" }, openGraph: { title: "Cash for Cars Elnora | Whole-Yard Pickup", description: "Free rural pickup for grain trucks, field cars and whole farmyard vehicle groups around Elnora.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-elnora", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Long-sitting farmyard vehicle near Elnora" }] } };
const data = {
  city: "Elnora", path: "/cash-for-cars-elnora", distance: "58 km", route: "Highway 21",
  heroTitle: "Cash for Cars Elnora — Whole Yards Welcome", heroText: "Forty-eight minutes southeast on Highway 21. One truck or eight, running or long dead—we come to the yard, pay on the spot and charge nothing for towing.",
  heroImage: heroPhoto, heroAlt: "Long-sitting vehicle in an Elnora farmyard", secondaryImage: yardPhoto, secondaryAlt: "Multiple farm vehicles accepted near Elnora",
  localTitle: "Farmyards Keep Everything", localIntro: "Generations of working vehicles can remain on the same farm because there was always a more urgent job and no easy way to move them.",
  localFactors: [{ title: "Vehicles that came with the place", text: "Grandad's truck, its replacement, a 1990s parts car and a grain truck that stopped one day may all remain through a farm sale or succession. We assess the group as it sits." }, { title: "Quoting a yard, not a car", text: "You do not need a complete inventory. Tell us roughly how many, identify what you can and describe access. One or two planned visits can clear the lot." }, { title: "What long-sitting costs", text: "Decades outside mean frame rust, rodent damage and few reusable parts. Much of the remaining value is weight—but it is still a real number and towing remains free." }],
  buyTypes: "Grain trucks, half-tons, 3/4-tons, one-tons, diesel pickups, farm and service vehicles, cars, SUVs, vans, commercial and fleet units.", buyConditions: "No-starts, seized engines, failed transmissions, hail, collision, write-offs, rusted-through frames, failed inspections, stripped shells and vehicles stationary for decades.",
  offers: [["Long-sitting shell, stripped or rotted", "$150 – $400"], ["Field car, complete but weathered", "$250 – $650"], ["Farm half-ton, non-running", "$500 – $1,500"], ["Grain truck or one-ton, complete", "$900 – $2,800"], ["High-kilometre runner", "$800 – $3,500"], ["Four or more from one yard", "Per-vehicle offer improves"]] as const,
  valueText: "Grain trucks carry substantial material weight. Parts and catalytic converter content add value when they remain usable, but years outside usually reduce both. The quoted group price includes every required pickup trip.",
  accessTitle: "Where We Collect", accessIntro: "Every Elnora address plus farms and acreages across southeastern Red Deer County are included.", accessItems: [{ title: "Village and farmland", text: "Highways 21, 590 and 585, Content Bridge, Pine Lake and the range roads between them." }, { title: "The whole yard", text: "Behind quonsets, past bins, treelines, field edges and rows along fences are routine working locations." }, { title: "Firm-ground access", text: "We go as far as the surface safely carries the truck and return later rather than rut farm land." }],
  process: "For one vehicle, send the year, make, model and condition. For a yard, estimate the count and describe what is visible. Offers return the same day; pickup is generally next day with a defined window.", paperwork: "We complete the bill of sale. Old farmyard vehicles often have lost documents, informal transfers or a deceased registered owner. Most situations are workable, but requirements must be established before dispatch.",
  nearby: [["Delburne", "22 km northwest"], ["Stettler", "40 km northeast"], ["Alix", "45 km north"], ["Trochu", "25 km south"], ["Red Deer County", "All farms included"]] as const,
  faqs: [["I have eight vehicles and cannot identify most of them.", "That is fine. Describe what you can and we will quote the group without requiring a formal inventory."], ["Some have no paperwork at all.", "Very common. Call first; most situations have a documentation route."], ["They have been sitting since the eighties.", "Expect the lower end, but the offer is real and removal remains free."], ["Do you buy grain trucks?", "Yes. Their substantial weight often creates a stronger offer."], ["Is there a charge to come this far?", "No mileage fee, minimum value or pickup deduction."], ["Can you take all of them in one trip?", "It depends on count. We disclose the visit plan upfront and price the entire group together."]] as const,
  finalTitle: "Get a Number for the Whole Yard",
};
export default function Page(){return <LocationPage data={data}/>;}
