import type { Metadata } from "next";
import heroPhoto from "@/assets/black-sedan-junkyard.jpeg";
import corridorPhoto from "@/assets/junk-pickup-free-towing.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Bowden AB | Free Towing & Instant Cash", description: "Cash for cars in Bowden, Alberta. We buy high-kilometre commuters, non-runners, scrap and damaged vehicles, tow free, and pay you when we collect.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-bowden" }, openGraph: { title: "Cash for Cars Bowden | Free QEII Pickup", description: "Cash offers and free towing for high-kilometre, rusted and damaged vehicles throughout Bowden.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-bowden", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "High-kilometre vehicle purchased for cash in Bowden" }] } };
const data = {
  city: "Bowden", path: "/cash-for-cars-bowden", distance: "48 km", route: "QEII",
  heroTitle: "Cash for Cars Bowden — Free QEII Towing", heroText: "Thirty-five minutes north of you on Highway 2. Running, seized, damaged or scrap—one number that includes towing and cash before the vehicle moves.",
  heroImage: heroPhoto, heroAlt: "Older highway commuter ready for pickup near Bowden", secondaryImage: corridorPhoto, secondaryAlt: "Free flat-deck towing serving Bowden",
  localTitle: "Living Beside a Freeway Costs Vehicles", localIntro: "Commuting both north and south combines high annual kilometres with months of freeway spray and accelerated underbody corrosion.",
  localFactors: [{ title: "Commuting goes both ways", text: "Red Deer, Olds, Didsbury and Calgary commutes can add twenty thousand kilometres a year or more. That ends dealer interest long before it erases parts and material value." }, { title: "Highway spray is worse", text: "Continuous brine at freeway speed reaches wheel wells, rockers, brake and fuel lines and every underbody seam. Bowden vehicles often rust faster than town-only cars." }, { title: "Corridor commercial traffic", text: "Highway 2 service-road businesses retire work trucks and service units when contracts end. Several vehicles at one address improve collection efficiency." }],
  buyTypes: "Cars, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesel pickups, farm and work trucks, vans, commercial and fleet vehicles.", buyConditions: "No-starts, failed engines or transmissions, hail, collision, write-offs, fire, flood, rusted-through frames, failed inspections and partly stripped vehicles.",
  offers: [["Rusted-out car, non-running", "$200 – $600"], ["Older car, complete, non-running", "$250 – $800"], ["High-kilometre highway commuter", "$800 – $3,500"], ["Half-ton or work truck, non-running", "$600 – $2,000"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck, SUV or car", "$3,000 – $15,000"]] as const,
  valueText: "Weight and reusable parts establish value, while frame corrosion is the strongest downward pressure here. Describe the underside honestly so the first quote is accurate. Towing remains included even at the low end.",
  accessTitle: "Where We Collect", accessIntro: "Town addresses, the Highway 2 corridor and surrounding Red Deer County farms and acreages are all covered.", accessItems: [{ title: "Town and corridor", text: "Every Bowden neighbourhood plus service-road shops, commercial lots and retired fleet vehicles." }, { title: "County properties", text: "Highways 2A and 587 and nearby range roads, including gravel approaches and farm yards." }, { title: "Field and soft-ground access", text: "Field pickups are normal when conditions support the truck. We reschedule rather than rut a property." }],
  process: "Call or submit the year, make, model and honest condition. We return a same-day offer and usually collect the same day or next.", paperwork: "We prepare the bill of sale. Company vehicles, estates and vehicles with liens are workable when discussed before pickup rather than discovered on site.",
  nearby: [["Innisfail", "16 km north"], ["Olds", "22 km south"], ["Penhold", "32 km north"], ["Spruce View", "35 km northwest"], ["Red Deer County", "Rural pickup included"]] as const,
  faqs: [["The frame is badly rusted. Will you still take it?", "Yes. Rust lowers the value but the vehicle retains material and parts value, and towing remains free."], ["My car has enormous highway kilometres.", "Kilometres affect us far less than a dealer because weight and parts do not depend on remaining road life."], ["Any charge for the trip?", "None. No mileage fee or minimum value."], ["Do you buy work trucks and service units?", "Regularly, one at a time or in groups."], ["Can you collect from a service-road business?", "Yes. Commercial and fleet pickups are routine."], ["How quickly can you get here?", "About thirty-five minutes. Morning calls normally qualify for same-day pickup."]] as const,
  finalTitle: "Get a Quote",
};
export default function Page(){return <LocationPage data={data}/>;}
