import type { Metadata } from "next";
import heroPhoto from "@/assets/used-suv-red-deer.jpeg";
import farmPhoto from "@/assets/abandoned-sedan-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Olds AB | Free Towing, Same-Day Pickup", description: "Cash for cars in Olds, Alberta. We buy running, junk, scrap, student and farm vehicles, tow free, and pay at pickup. No trip charge from Red Deer.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-olds" }, openGraph: { title: "Cash for Cars Olds AB | No Trip Charge", description: "Free towing and cash offers for student, farm and everyday vehicles throughout Olds.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-olds", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Used vehicle purchased for cash in Olds" }] } };
const data = {
  city: "Olds", path: "/cash-for-cars-olds", distance: "70 km", route: "QEII",
  heroTitle: "Cash for Cars Olds — No Trip Charge", heroText: "Olds is seventy kilometres from us and we come anyway, at no cost to you. Running or seized, town or county—one offer that already includes the tow.",
  heroImage: heroPhoto, heroAlt: "Used SUV purchased for cash near Olds", secondaryImage: farmPhoto, secondaryAlt: "Long-sitting vehicle on a Mountain View County property",
  localTitle: "You Have Options in Olds—Here Is Ours", localIntro: "Calgary and Red Deer buyers both serve Olds. The useful comparison is not the first number spoken—it is the amount actually paid after towing.",
  localFactors: [{ title: "The Calgary question", text: "Get more than one quote. Neither direction has a structural distance advantage, but our figure includes towing and is not reduced on arrival. Compare final, in-hand numbers." }, { title: "A college town's vehicles", text: "Olds College brings inexpensive student cars that may not survive a second winter. For abandoned rental vehicles, ownership documents—not removal—are the hurdle." }, { title: "Mountain View County agriculture", text: "Grain trucks, gravel-road half-tons, service units and retired farm vehicles create steady turnover across the surrounding working land." }],
  buyTypes: "Cars, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesel pickups, grain and farm trucks, minivans, cargo vans, commercial and fleet vehicles.", buyConditions: "No-starts, failed engines or transmissions, hail, collision, write-offs, fire, flood, frame rust, failed inspections, partly stripped and simply finished vehicles.",
  offers: [["Older student car, non-running", "$200 – $700"], ["Older car, complete, non-running", "$250 – $800"], ["Farm or work truck, non-running", "$600 – $2,000"], ["High-kilometre runner", "$800 – $3,500"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck, SUV or car", "$3,000 – $15,000"]] as const,
  valueText: "Weight comes first, then reusable drivetrain, panels, glass, wheels and catalytic converter content. Frame and rocker rust reduce the number, while completeness protects it. The full seventy-kilometre tow is already included.",
  accessTitle: "Where We Collect", accessIntro: "Every Olds neighbourhood, commercial area and surrounding Mountain View County property is covered.", accessItems: [{ title: "In town", text: "Residential streets, the older core, Uptowne, the commercial strip, Netook Crossing and Highway 2 service-road industrial properties." }, { title: "Student and rental properties", text: "Cars left at rentals are removable when the correct right-to-dispose documentation is in place." }, { title: "Mountain View County", text: "Highways 27 and 2A, range roads, farms and acreages. Gravel and field access are routine; genuinely soft ground may require rescheduling." }],
  process: "Call or submit the year, make, model and condition. Offers return the same day. Olds pickups are usually next day because of distance, though same-day service happens when routing allows.", paperwork: "We prepare the bill of sale. Student cars, estates and out-of-province registrations are common here and each is easier to resolve before a truck is dispatched.",
  nearby: [["Bowden", "22 km north"], ["Innisfail", "37 km north"], ["Spruce View", "40 km northwest"], ["Red Deer", "70 km north"], ["Mountain View County", "Rural pickup included"]] as const,
  faqs: [["Do you charge extra to come seventy kilometres?", "No mileage fee, trip charge or minimum value. Towing is inside the offer."], ["Should I call a Calgary buyer instead?", "Get both quotes. Compare the amount actually paid after every deduction."], ["A student left a car at my rental property.", "Common in Olds. You need documentation proving the right to dispose of it; call and we will explain."], ["Do you buy grain trucks?", "Yes. Their weight generally works in your favour."], ["The car is registered in another province.", "Usually workable. Mention it when calling so we know which documents to expect."], ["How long before you can get here?", "Usually next day. Tell us about deadlines and we will try to accommodate same-day pickup."], ["It has not run in years and the tires are flat.", "Routine. We bring a winch and skates."]] as const,
  finalTitle: "Get a Quote",
};
export default function Page(){return <LocationPage data={data}/>;}
