import type { StaticImageData } from "next/image";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeDollarSign, CalendarClock, Car, Check, ChevronDown, ChevronRight, ClipboardCheck, KeyRound, MapPin, Menu, Phone, Route, ShieldCheck, Truck, Wrench } from "lucide-react";
import logo from "@/assets/junkmycarreddeer_red-logo.png";
import { QuoteForm } from "@/components/quote-form";
import { BreadcrumbSchema, JsonLd } from "@/components/seo-schema";
import styles from "@/app/cash-for-cars-sylvan-lake/page.module.css";

type Item = { title: string; text: string };
type LocationService = { title: string; before: string; after: string; href: string; linkLabel: string };
type LocationPageData = {
  city: string; path: string; distance: string; route: string; heroTitle: string; heroText: string;
  heroImage: StaticImageData; heroAlt: string; secondaryImage: StaticImageData; secondaryAlt: string;
  localTitle: string; localIntro: string; localFactors: Item[];
  buyTypes: string; buyConditions: string;
  offers: readonly (readonly [string, string])[]; valueText: string;
  servicesIntro?: string; services?: LocationService[];
  accessTitle: string; accessIntro: string; accessItems: Item[];
  process: string; paperwork: string; nearby: readonly (readonly [string, string])[];
  faqs: readonly (readonly [string, string])[]; finalTitle: string;
};

const phoneDisplay = "(403) 427-0732";
const phoneHref = "tel:+14034270732";

export function LocationPage({ data }: { data: LocationPageData }) {
  const schemas = [
    { "@context": "https://schema.org", "@type": "Service", "@id": `https://www.junkmycarreddeer.ca${data.path}#service`, name: `Cash for Cars ${data.city}`, description: data.heroText, url: `https://www.junkmycarreddeer.ca${data.path}`, serviceType: "Cash vehicle buying and free vehicle removal", provider: { "@id": "https://www.junkmycarreddeer.ca/#business" }, areaServed: { "@type": "City", name: data.city, containedInPlace: { "@type": "AdministrativeArea", name: "Alberta" } }, availableChannel: { "@type": "ServiceChannel", servicePhone: { "@type": "ContactPoint", telephone: "+1-403-427-0732", contactType: "sales", areaServed: "CA-AB", availableLanguage: "English" } }, offers: { "@type": "Offer", priceCurrency: "CAD", description: "No-obligation vehicle offer with free towing included" } },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": `https://www.junkmycarreddeer.ca${data.path}#faq`, url: `https://www.junkmycarreddeer.ca${data.path}`, mainEntity: data.faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) },
  ];
  return <>
    <a className="skip-link" href="#main">Skip to main content</a>
    <div className="utility-bar"><div className="shell utility-inner"><span><MapPin aria-hidden="true" /> {data.city} &amp; surrounding properties</span><span className="utility-promise">{data.distance} from Red Deer · Same-day pickup available</span><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div></div>
    <header className="site-header"><div className="shell header-inner"><Link className="brand" href="/"><Image src={logo} alt="Junk My Car Red Deer" priority sizes="190px" /></Link><nav className="desktop-nav"><a href="#local">Why vehicles accumulate</a><a href="#buy">What we buy</a><a href="#value">What it is worth</a>{data.services && <a href="#services">Services</a>}<a href="#coverage">Local pickup</a><a href="#questions">FAQ</a></nav><a className="button button-header" href="#location-quote">Get my offer <ArrowRight aria-hidden="true" /></a><details className="menu-button"><summary aria-label="Open navigation"><Menu aria-hidden="true" /></summary><nav><a href="#local">Local vehicle patterns</a><a href="#buy">What we buy</a><a href="#value">Vehicle values</a>{data.services && <a href="#services">Services</a>}<a href="#coverage">Local pickup</a><a href="#questions">FAQ</a></nav></details></div></header>
    <main id="main" className={styles.page}>
      <section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div className={styles.heroCopy}><nav className={styles.breadcrumb}><Link href="/">Home</Link><ChevronRight aria-hidden="true" /><span>Cash for Cars {data.city}</span></nav><p className={styles.kicker}><MapPin aria-hidden="true" /> {data.city}, Alberta</p><h1>{data.heroTitle}</h1><p>{data.heroText}</p><div className={styles.heroActions}><a className="button button-primary" href="#location-quote">Get My Offer <ArrowRight aria-hidden="true" /></a><a href={phoneHref}><Phone aria-hidden="true" /> Call {phoneDisplay}</a></div><div className={styles.heroProof}><span><Check aria-hidden="true" /> Free town &amp; county towing</span><span><Check aria-hidden="true" /> Cash or e-transfer at pickup</span></div></div><div className={styles.heroVisual}><Image src={data.heroImage} alt={data.heroAlt} fill priority sizes="(max-width: 900px) 100vw, 46vw" /><div className={styles.heroShade} /><div className={styles.routeCard}><Route aria-hidden="true" /><span><small>Red Deer to {data.city}</small><strong>{data.distance} via {data.route}</strong></span></div></div></div></section>
      <section id="location-quote" className={styles.quoteSection}><div className={`shell ${styles.quotePanel}`}><QuoteForm /></div></section>
      <section id="local" className={styles.localSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>The local pattern</p><h2>{data.localTitle}</h2><p>{data.localIntro}</p></div><div className={styles.factorGrid}>{data.localFactors.map((item, index) => <article key={item.title}>{index === 0 ? <Car aria-hidden="true" /> : index === 1 ? <Truck aria-hidden="true" /> : <Route aria-hidden="true" />}<h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
      <section id="buy" className={styles.buySection}><div className={styles.buyImage}><Image src={data.secondaryImage} alt={data.secondaryAlt} fill sizes="(max-width: 850px) 100vw, 46vw" /><div><Truck aria-hidden="true" /><span>Running or not.<strong>We bring the equipment.</strong></span></div></div><div className={styles.buyCopy}><p className={styles.kicker}>Almost any vehicle</p><h2>What We Take</h2><article><Car aria-hidden="true" /><div><h3>Vehicle types</h3><p>{data.buyTypes}</p></div></article><article><Wrench aria-hidden="true" /><div><h3>Conditions</h3><p>{data.buyConditions}</p></div></article><a href="/what-we-buy">See the complete vehicle list <ArrowRight aria-hidden="true" /></a></div></section>
      <section id="value" className={styles.valueSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>Realistic local ranges</p><h2>What {data.city} Sellers Get Paid</h2></div><div className={styles.valueGrid}><div className={styles.offerTable}><div className={styles.tableHead}><span>Vehicle</span><span>Typical offer</span></div>{data.offers.map(([vehicle, offer]) => <div key={vehicle}><span>{vehicle}</span><strong>{offer}</strong></div>)}</div><aside><BadgeDollarSign aria-hidden="true" /><h3>What we are looking at</h3><p>{data.valueText}</p><p><strong>The tow is already included.</strong> We do not deduct it or renegotiate an accurately described vehicle in your driveway.</p></aside></div></div></section>
      {data.services && data.servicesIntro && <section id="services" className={styles.servicesSection}><div className="shell"><div className={styles.servicesIntro}><div><p className={styles.kicker}>Six ways we can help</p><h2>Our Services in {data.city}</h2></div><p>{data.servicesIntro}</p></div><div className={styles.serviceGrid}>{data.services.map((service, index) => <article key={service.title}><span className={styles.serviceNumber}>{String(index + 1).padStart(2, "0")}</span>{index === 0 ? <Truck aria-hidden="true" /> : index === 1 ? <Wrench aria-hidden="true" /> : index === 2 ? <BadgeDollarSign aria-hidden="true" /> : index === 3 ? <ShieldCheck aria-hidden="true" /> : index === 4 ? <Car aria-hidden="true" /> : <Route aria-hidden="true" />}<h3>{service.title}</h3><p>{service.before}<Link href={service.href}>{service.linkLabel} <ArrowRight aria-hidden="true" /></Link>{service.after}</p></article>)}</div></div></section>}
      <section id="coverage" className={styles.coverageSection}><div className={`shell ${styles.coverageGrid}`}><div><p className={styles.kicker}>The awkward ones included</p><h2>{data.accessTitle}</h2><p>{data.accessIntro}</p><div className={styles.areaCards}>{data.accessItems.map((item, index) => <article key={item.title}>{index === 0 ? <MapPin aria-hidden="true" /> : index === 1 ? <Route aria-hidden="true" /> : <Truck aria-hidden="true" />}<h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div><aside><h3>Communities nearby</h3><p>Free towing also reaches:</p><div>{data.nearby.map(([place, detail]) => <span key={place}>{place}<strong>{detail}</strong></span>)}</div><p>Every acreage and rural property between them is included too.</p></aside></div></section>
      <section className={styles.processSection}><div className="shell"><div className={styles.sectionHeading}><p className={styles.kicker}>From call to cash</p><h2>The Process</h2><p>{data.process}</p></div><div className={styles.processGrid}><article><KeyRound aria-hidden="true" /><h3>Before we arrive</h3><p>Empty the vehicle, remove your plate and have photo ID plus proof of ownership ready. You do not need to clean, start or move it.</p></article><article><CalendarClock aria-hidden="true" /><h3>On the day</h3><p>We confirm the description, complete the bill of sale, pay by cash or e-transfer and load it. Most appointments take twenty minutes.</p></article><article><ClipboardCheck aria-hidden="true" /><h3>After the sale</h3><p>Take your plate and bill of sale to a registry agent, then call your insurer about any unused prepaid coverage.</p></article></div><div className={styles.paperwork}><ShieldCheck aria-hidden="true" /><div><h3>Alberta paperwork</h3><p>{data.paperwork}</p></div></div></div></section>
      <section id="questions" className={styles.faqSection}><div className={`shell ${styles.faqGrid}`}><div><p className={styles.kicker}>Local questions</p><h2>{data.city} FAQs</h2><p>Answers about pickup timing, access, ownership and vehicle condition.</p><a href={phoneHref}><Phone aria-hidden="true" /> Ask us directly</a></div><div>{data.faqs.map(([q, a], index) => <details key={q} open={index === 0}><summary><span>{q}</span><ChevronDown aria-hidden="true" /></summary><p>{a}</p></details>)}</div></div></section>
      <section className={styles.finalSection}><div className={`shell ${styles.finalGrid}`}><div><p className={styles.kicker}>Enough to start</p><h2>{data.finalTitle}</h2><p>Year, make, model and a rough description is all we need.</p></div><div><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a><a href="#location-quote">Get a Free Offer <ArrowRight aria-hidden="true" /></a></div></div></section>
    </main>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><Image src={logo} alt="Junk My Car Red Deer" sizes="230px" /><p>Cash offers and free vehicle towing throughout {data.city} and Central Alberta.</p><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div><div><h3>Services</h3><Link href="/junk-car-removal-red-deer">Junk Car Removal</Link><Link href="/scrap-car-removal-red-deer">Scrap Car Removal</Link><Link href="/sell-my-car-red-deer">Sell My Car</Link><Link href="/free-towing-red-deer">Free Towing</Link></div><div><h3>Company</h3><Link href="/about">About Us</Link><Link href="/how-it-works">How It Works</Link><Link href="/what-we-buy">What We Buy</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></div><div><h3>Visit or contact</h3><p>4909 48 Street<br />Red Deer, AB T4N 1S8</p><a className="footer-quote" href="#location-quote">Request a quote <ArrowRight aria-hidden="true" /></a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Junk My Car Red Deer</span><span>Serving {data.city} &amp; Central Alberta</span></div></footer>
    <div className="mobile-actions"><a href={phoneHref}><Phone aria-hidden="true" /> Call now</a><a href="#location-quote"><BadgeDollarSign aria-hidden="true" /> Get offer</a></div>
    <BreadcrumbSchema current={`Cash for Cars ${data.city}`} path={data.path} />
    {schemas.map((schema, index) => <JsonLd key={index} data={schema} />)}
  </>;
}
