import type { Metadata } from "next";
import heroPhoto from "@/assets/older-ford-f150-acreage.jpeg";
import ranchPhoto from "@/assets/old-chevrolet-suburban-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Ponoka | Top Dollar, Free Towing", description: "Cash for cars and trucks Ponoka, Alberta. We buy ranch trucks, non-runners, scrap and damaged vehicles, tow free from town and county, and pay on pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-ponoka" }, openGraph: { title: "Cash for Cars and Trucks Ponoka | Free Towing", description: "Cash paid for ranch trucks, work vehicles and cars throughout Ponoka and Ponoka County.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-ponoka", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Ranch truck ready for cash pickup near Ponoka" }] } };
const data = {
  city: "Ponoka", path: "/cash-for-cars-ponoka", distance: "55 km", route: "QEII",
  heroTitle: "Cash for Cars & Trucks Ponoka — Paid at Pickup", heroText: "Forty minutes north on the QEII. We buy ranch trucks, work vehicles, cars and everything between—running or seized, in town or twelve miles down a range road.",
  heroImage: heroPhoto, heroAlt: "Older ranch truck on a Central Alberta property", secondaryImage: ranchPhoto, secondaryAlt: "Long-sitting vehicle on a Ponoka County property",
  localTitle: "Towing Wears a Truck Differently", localIntro: "Ponoka trucks often work behind stock trailers, goosenecks and equipment floats. That history appears in drivetrains more than odometers.",
  localFactors: [{ title: "What a life of pulling does", text: "Transmissions, rear ends, front ends and brakes carry the load. A tired-drivetrain 3/4-ton is still heavy and parts-rich, so towing history reduces our value far less than it does a dealer's." }, { title: "Stampede and event traffic", text: "The Calnash Ag Event Centre and stampede grounds bring vehicles through town that sometimes never leave after a breakdown, write-off or retirement. We can collect them without a long explanation." }, { title: "Ranch and county accumulation", text: "A retired truck kept for parts becomes a row along the fence line. Several vehicles mean one efficient trip and generally a better per-vehicle offer." }],
  buyTypes: "Half-tons, 3/4-tons, one-tons, duallies, diesel pickups, ranch and farm trucks, stock and service vehicles, cars, SUVs, vans, commercial units and fleets.", buyConditions: "No-starts, failed engines, transmissions or rear ends, hail, collision, write-offs, fire, flood, frame rust, failed inspections and partly stripped vehicles all qualify.",
  offers: [["Older car, non-running, complete", "$250 – $800"], ["Half-ton, non-running, complete", "$600 – $1,800"], ["3/4-ton or one-ton, non-running", "$900 – $2,800"], ["Diesel or dually, complete", "$1,200 – $4,000"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck or SUV", "$3,000 – $15,000"], ["Three or more from one property", "Per-vehicle offer improves"]] as const,
  valueText: "A one-ton carries close to twice the recoverable steel of a midsize car. Transfer cases, differentials, boxes, tailgates, hubs and diesel parts also move steadily. An intact truck catalytic converter can be a major line item.",
  servicesIntro: "Ranch truck with a towing-worn drivetrain, a vehicle left behind after a stampede weekend, or a whole fence line of retired units—each service below covers Ponoka and Ponoka County, with free towing and payment on collection.",
  services: [
    { title: "Junk Car Removal in Ponoka", before: "Trucks that broke down during an event at the Calnash Ag Event Centre and were never hauled home turn up here every year. Our ", linkLabel: "junk car removal service", href: "/junk-car-removal-red-deer", after: " collects them from town lots, the event-ground area or wherever they were parked—no long explanation needed." },
    { title: "Scrap Car Removal in Ponoka", before: "A ranch truck kept for parts, then picked over for a decade, eventually has nothing left but weight—and a one-ton carries plenty of it. Our ", linkLabel: "scrap car removal", href: "/scrap-car-removal-red-deer", after: " clears stripped units from shelterbelts and quonset yards and processes them properly, oils and coolant captured first." },
    { title: "Sell My Car in Ponoka", before: "A running half-ton that has pulled stock trailers for years scares off private buyers the moment they hear “towing.” Our ", linkLabel: "sell my car service", href: "/sell-my-car-red-deer", after: " prices it on what it actually is—a heavy, parts-rich truck—and pays you in one visit." },
    { title: "Damaged and Write-Off Vehicles in Ponoka", before: "Livestock country means wildlife and trailer mishaps as well as hail. Our ", linkLabel: "damaged car buying service", href: "/damaged-car-removal-red-deer", after: " buys collision, hail and insurance buyback vehicles—salvage and non-repairable both—and values the drivetrain the damage did not reach." },
    { title: "Car Wreckers Serving Ponoka", before: "Transfer cases, rear ends, hubs, gooseneck hitches and diesel components from Ponoka ranch trucks are exactly what other operators across Central Alberta go looking for. As ", linkLabel: "car wreckers", href: "/car-wreckers-red-deer", after: " we recover those parts, which is why a dead-engine dually still earns a strong number." },
    { title: "Free Towing in Ponoka", before: "Forty minutes up the QEII and twelve miles down a range road off Highway 53—still no charge. ", linkLabel: "Free towing", href: "/free-towing-red-deer", after: " covers town and all of Ponoka County, including five-truck fence-line clear-outs quoted as one lot." },
  ],
  accessTitle: "Where We Come", accessIntro: "Every Ponoka address plus ranches, farms and acreages well beyond the pavement are included without a mileage fee.", accessItems: [{ title: "In Ponoka", text: "Residential streets, the older core, Highway 2A commercial properties and the light-industrial area—driveways, yards, shop lots and rented stalls." }, { title: "Ponoka County", text: "Highways 53, 2A and 822 plus the range roads, long approaches, fields, quonsets and shelterbelts." }, { title: "Ground conditions", text: "Soft ground is the real limit. If access would rut the property, we return when it firms rather than cause damage." }],
  process: "Call or send the year, make, model and what failed. We return a same-day offer and normally collect the same day or next despite the distance because the QEII run is direct.", paperwork: "We complete the bill of sale. Farm vehicles may be registered to a corporation, estate or former partnership; mention ownership when calling so signing authority can be confirmed before dispatch.",
  nearby: [["Lacombe", "30 km south"], ["Rimbey", "40 km west"], ["Bentley", "35 km southwest"], ["Red Deer", "55 km south"], ["Ponoka County", "All rural properties"]] as const,
  faqs: [["The transmission is gone but the truck is otherwise solid.", "That is one of our most common purchases. The remaining weight and parts protect much of the value."], ["Do you buy duallies and one-tons?", "Yes. Heavy vehicles with strong parts demand are among our higher offers."], ["There are five trucks along my fence line.", "We can quote the entire group and collect them efficiently."], ["How far out will you come?", "Anywhere in Ponoka County, including well off pavement, with no mileage charge."], ["Do you take stock or horse trailers?", "Sometimes, depending on condition and registration. Describe them for a direct answer."], ["It is registered to the farm corporation.", "Workable with the right signing authority and documentation. Call first."], ["How long does the drive take?", "About forty minutes. Same-day pickup is still normal when scheduling allows."]] as const,
  finalTitle: "Get a Number",
};
export default function Page(){return <LocationPage data={data}/>;}
