import type { Metadata } from "next";
import heroPhoto from "@/assets/old-chevrolet-suburban-acreage.jpeg";
import workPhoto from "@/assets/older-ford-f150-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Rimbey | Free Towing & Cash Offers", description: "Cash for cars in Rimbey, Alberta. We buy high-mileage, non-running, scrap and damaged vehicles, tow free from town and county, and pay at pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-rimbey" }, openGraph: { title: "Cash for Cars Rimbey | Free County Towing", description: "Cash offers for high-mileage cars, service trucks and farm vehicles throughout Rimbey and western Ponoka County.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-rimbey", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "High-mileage vehicle ready for pickup near Rimbey" }] } };
const data = {
  city: "Rimbey", path: "/cash-for-cars-rimbey", distance: "68 km", route: "Highway 20",
  heroTitle: "Cash for Cars Rimbey — County Towing Included", heroText: "Fifty minutes northwest on Highway 20. We buy high-kilometre vehicles, non-runners, work trucks and write-offs—free towing and cash on collection anywhere in the county.",
  heroImage: heroPhoto, heroAlt: "Older high-kilometre vehicle near Rimbey", secondaryImage: workPhoto, secondaryAlt: "Older service truck accepted for cash near Rimbey",
  localTitle: "Everything Here Is a Drive", localIntro: "Rimbey serves a large, sparsely populated area, so ordinary vehicles accumulate extraordinary kilometres and gravel-road wear.",
  localFactors: [{ title: "The mileage adds up quietly", text: "Groceries, work, appointments and hockey all involve distance. Twenty-five to thirty thousand kilometres a year is normal, and dealers stop offering meaningful trade value long before the vehicle stops being useful for parts and material." }, { title: "Gravel takes its own toll", text: "Range roads produce chipped glass, suspension and steering wear, dust intrusion and undercarriage damage that an odometer never shows." }, { title: "Energy and agriculture overlap", text: "Service trucks, crew cabs, farm half-tons, grain trucks and equipment-hauling one-tons retire here. Heavy, parts-rich units are our strongest non-running purchases." }],
  buyTypes: "Cars, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesel and service trucks, grain and farm trucks, vans, commercial units and fleets.", buyConditions: "No-starts, failed engines or transmissions, hail, collision, write-offs, fire, flood, frame rust, failed inspections and partly stripped vehicles.",
  offers: [["Older car, complete, non-running", "$250 – $800"], ["High-kilometre runner", "$800 – $3,500"], ["Half-ton, non-running, complete", "$600 – $1,800"], ["Service truck or one-ton, non-running", "$900 – $3,000"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck, SUV or car", "$3,000 – $15,000"]] as const,
  valueText: "Weight establishes the floor. Reusable parts and catalytic converter content create the upside; on a heavy truck the converter can be worth more than the remaining shell. Rust and missing components reduce it. The sixty-eight-kilometre tow is included.",
  accessTitle: "Where We Come", accessIntro: "Every Rimbey address plus farms and acreages across western Ponoka County are inside the free pickup area.", accessItems: [{ title: "In town", text: "Residential streets, Main Street, commercial yards and the light-industrial district around Highways 20 and 53." }, { title: "County and rural", text: "Properties toward Bluffton, Hoadley and the Blindman River, including gravel approaches, fields and vehicles behind quonsets." }, { title: "Off the pavement", text: "We go as far as required when the ground supports a loaded truck. Soft conditions may require a return visit." }],
  process: "Call or submit the year, make, model and honest condition. Offers return the same day; pickups are usually next day with a defined time window because of distance.", paperwork: "We prepare the bill of sale. Farm-corporation and company vehicles are common and workable when signing authority is confirmed before dispatch.",
  nearby: [["Bentley", "25 km southeast"], ["Ponoka", "40 km east"], ["Eckville", "35 km south"], ["Red Deer", "68 km southeast"], ["Ponoka County", "Rural pickup included"]] as const,
  faqs: [["My vehicle has extremely high kilometres. Is it worth anything?", "Yes. We price weight, parts and material rather than remaining service life, so kilometres matter far less to us than to a dealer."], ["Do you charge to come sixty-eight kilometres?", "No mileage fee, minimum value or pickup deduction."], ["Do you buy service and welding trucks?", "Yes. Weight and parts demand often put them near the top of our non-running range."], ["It is registered to the farm.", "Workable with the right documents and signing authority. Call first."], ["How far off pavement will you go?", "As far as needed when the ground will carry the truck."], ["Several vehicles on one property?", "One efficient trip generally improves the per-vehicle offer."]] as const,
  finalTitle: "Get a Quote",
};
export default function Page(){return <LocationPage data={data}/>;}
