import type { Metadata } from "next";
import heroPhoto from "@/assets/older-ford-f150-acreage.jpeg";
import lakePhoto from "@/assets/abandoned-sedan-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Bentley AB | Free Towing & Cash Paid", description: "Cash for cars in Bentley, Alberta. We buy farm trucks, non-runners, scrap and damaged vehicles, tow free from the village and county, and pay on pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-bentley" }, openGraph: { title: "Cash for Cars Bentley | Farm Trucks Welcome", description: "Cash offers and free pickup across Bentley, Gull Lake and surrounding Lacombe County farms.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-bentley", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Farm truck ready for cash pickup near Bentley" }] } };
const data = {
  city: "Bentley", path: "/cash-for-cars-bentley", distance: "42 km", route: "Highway 12",
  heroTitle: "Cash for Cars Bentley — County Towing Included", heroText: "Thirty-five minutes from Red Deer on Highway 12. Farm trucks, cars, work vehicles and write-offs—one number that includes towing, paid when we load it.",
  heroImage: heroPhoto, heroAlt: "Older farm truck on a Bentley-area property", secondaryImage: lakePhoto, secondaryAlt: "Seasonal vehicle ready for removal near Gull Lake",
  localTitle: "Where a Truck Is a Tool", localIntro: "Around Bentley, vehicles serve cattle, hay and grain operations first and transportation second. They are demoted through several jobs before finally retiring.",
  localFactors: [{ title: "Farm vehicles accumulate", text: "The good truck becomes the yard truck and then the parts truck. Clearing three or four along a fence line takes one visit and typically improves each offer." }, { title: "Yard use wears differently", text: "Low-speed, high-load work consumes clutches, transmissions, rear ends and front suspension before odometer numbers look high. Weight and parts value remain." }, { title: "Gull Lake in summer", text: "Aspen Beach and Gull Lake properties produce cheap seasonal cars eventually parked when they stop starting. Their value may be modest, but removal is free." }],
  buyTypes: "Half-tons, 3/4-tons, one-tons, diesel pickups, farm and grain trucks, cars, SUVs, crossovers, vans, work units and fleets.", buyConditions: "No-starts, failed engines, transmissions or rear ends, hail, collision, write-offs, fire, flood, frame rust, failed inspections and stripped vehicles.",
  offers: [["Older car, complete, non-running", "$250 – $800"], ["Farm half-ton, non-running", "$600 – $1,800"], ["3/4-ton, one-ton or grain truck", "$900 – $2,800"], ["High-kilometre runner", "$800 – $3,500"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Three or more, one property", "Per-vehicle offer improves"]] as const,
  valueText: "Farm trucks contain substantial recoverable steel. Reusable parts and catalytic converter content add value above weight; severe rust and missing components reduce it. The quoted number includes towing and stands on arrival.",
  accessTitle: "Where We Come", accessIntro: "Bentley, Gull Lake, Aspen Beach and the farms and acreages between them are all covered.", accessItems: [{ title: "Village and county", text: "Every Bentley address and rural property along Highways 12 and 20 and nearby range roads." }, { title: "Gull Lake properties", text: "Seasonal lots and cabin vehicles are included when an authorized person can sign and accept payment." }, { title: "Farm access", text: "Yards, fields, quonsets and shelterbelts are standard. Soft ground may require a later pickup to avoid ruts." }],
  process: "Call or submit the year, make, model and condition. We return a same-day offer and normally collect the same day or next.", paperwork: "We write the bill of sale. Farm corporations, estates and vehicles transferred informally within families are workable when the correct authority is arranged before dispatch.",
  nearby: [["Sylvan Lake", "24 km south"], ["Eckville", "22 km south"], ["Rimbey", "25 km northwest"], ["Lacombe", "22 km east"], ["Lacombe County", "All farms included"]] as const,
  faqs: [["The truck only worked in the yard. Is it worth anything?", "Yes. Low kilometres do not erase drivetrain wear, but it remains a heavy, parts-rich truck."], ["There are four trucks in the shelterbelt.", "We can quote and collect the group in one efficient visit."], ["Do you charge to come out here?", "No mileage fee, minimum value or pickup deduction."], ["Do you buy grain trucks?", "Yes. Their weight works in your favour."], ["It is registered to the farm corporation.", "Workable with proper signing authority. Call first."], ["Can you reach a Gull Lake property?", "Yes. An authorized person must be present to sign and accept payment."]] as const,
  finalTitle: "Get a Quote",
};
export default function Page(){return <LocationPage data={data}/>;}
