import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeDollarSign, Car, ChevronDown, ClipboardCheck, MapPin, Phone, ShieldCheck, Truck, Wrench } from "lucide-react";
import heroPhoto from "@/assets/used-suv-red-deer.jpeg";
import logo from "@/assets/junkmycarreddeer_red-logo.png";
import { QuoteForm } from "@/components/quote-form";
import { BreadcrumbSchema, JsonLd } from "@/components/seo-schema";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Cash for Cars Calgary | Any Condition, Paid on Pickup",
  description: "Cash for cars in Calgary — running, used, damaged or dead. One firm offer, free towing across the city, and payment before your vehicle leaves. No listings.",
  alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-calgary" },
  openGraph: { title: "Cash for Cars Calgary | Any Condition, Paid on Pickup", description: "One firm cash offer, free towing across Calgary and payment before your vehicle leaves.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-calgary", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "Used SUV available for cash purchase in Calgary" }] },
};

const phoneDisplay = "(403) 427-0732";
const phoneHref = "tel:+14034270732";
const offers = [["Older car, non-running, complete", "$300 – $900"], ["Running, 12+ years, needs major repair", "$700 – $3,000"], ["Out-of-province vehicle, failed Alberta inspection", "$800 – $5,000"], ["Second household car, running, high kilometres", "$1,500 – $6,000"], ["Hail or collision write-off, mechanically sound", "$1,500 – $8,000"], ["Newer running car, SUV or truck", "$5,000 – $20,000+"]] as const;
const painPoints = [
  ["The trade-in number that made no sense", "A dealer prices your trade on how easily it can be resold on their lot. A twelve-year-old sedan with 230,000 km, a warning light and cracked glass often earns only a few hundred dollars in purchase credit. We price weight, usable parts and the catalytic converter, so kilometres and cosmetics cost you less."],
  ["The Marketplace experience", "A large market brings messages, low offers, no-shows and strangers asking for test drives. Fake payment screenshots, overpayment scams and third-party pickup stories add real risk. A clean newer vehicle may reward patience; older, damaged and non-running vehicles rarely justify the time."],
  ["The out-of-province inspection that failed", "Older arrivals often fail Alberta inspection on rust, brakes, suspension, lights or glass. We buy them with their out-of-province registration; the failed inspection report can help us quote accurately. You do not need to repair or register the vehicle in Alberta first."],
  ["The second car nobody needs anymore", "Hybrid work, a move near the CTrain, a teenager leaving for school or a job change can turn a useful second car into an insured, registered parking expense. If it still runs, that usually improves the offer—it is not a reason to keep postponing the sale."],
] as const;
const services = [
  ["Sell My Car in Calgary", "/sell-my-car-red-deer", "sell my car service", "For a running high-kilometre commuter, surplus second car or vehicle a dealer valued at almost nothing. One written cash offer—no photos, strangers or test drives."],
  ["Junk Car Removal in Calgary", "/junk-car-removal-red-deer", "junk car removal service", "For a no-start, seized engine or vehicle parked since the last cold snap. We collect from driveways, lanes, parkades and rented stalls without needing keys or a boost."],
  ["Damaged Car and Write-Off Buying in Calgary", "/damaged-car-removal-red-deer", "damaged car buying service", "Hail, collision, flood or an insurance buyback. Salvage and non-repairable vehicles are accepted and priced for the healthy drivetrain and panels behind the damage."],
  ["Scrap Car Removal in Calgary", "/scrap-car-removal-red-deer", "scrap car removal", "When rust, age or damage have finished a vehicle, we price weight, non-ferrous metal and the converter, then process fluids, refrigerant, batteries and tires properly."],
  ["Car Wreckers Serving Calgary", "/car-wreckers-red-deer", "car wreckers", "Working parts hold much of a truck, SUV or AWD crossover's value. Proper dismantling and component recovery lets a complete vehicle earn more than a weight-only quote."],
  ["Free Towing Across Calgary", "/free-towing-red-deer", "Free towing", "Every quadrant and property type—suburban driveway, inner-city lane, industrial yard or edge acreage—with no mileage fee, minimum value or pickup deduction."],
] as const;
const situations = [
  ["I moved here from another province and my car failed inspection.", "Bring the out-of-province registration, photo ID and inspection report if you have it. You do not need to repair or register it in Alberta first."],
  ["I'm leaving Calgary and the car isn't coming with me.", "Book a few days ahead when possible. We pay before pickup so you can cancel registration and insurance before your move or flight."],
  ["My son's car died in Calgary, but we live in Central Alberta.", "The registered owner must sign in person or authorize someone in advance. Call first and we will explain the documentation so you can avoid a trip."],
  ["There's still a loan on it.", "Lien payouts are routine. If the offer covers the balance, it clears during the sale; otherwise we show you the gap before a truck is booked."],
  ["The condo board wants it out of the parkade.", "Tell us the building, level and clearance height. We coordinate around property-manager notice and the equipment that can enter."],
  ["It's been sitting at a body shop for weeks.", "Send the address and release authorization. We can collect directly so daily storage charges stop growing."],
] as const;
const faqs = [
  ["Do you only buy junk cars?", "No. We also buy running used vehicles, high-kilometre commuters, surplus second cars, expensive repair jobs and newer vehicles people want sold quickly."],
  ["My car is registered in BC or Ontario and failed the Alberta inspection. Can I still sell it?", "Yes. Bring the out-of-province registration and photo ID. You do not need to repair or register it in Alberta first."],
  ["Will your offer beat a dealer trade-in?", "It usually does on older, high-kilometre, damaged or non-running vehicles. A clean late-model trade can be competitive, so get both figures and compare."],
  ["How quickly can you pick up in Calgary?", "Same day for most morning calls and next day otherwise. Tell us about move-out or condo deadlines when booking."],
  ["Is there any charge for towing or coming into the city?", "None. No towing fee, mileage charge, minimum value or deduction at pickup."],
  ["The car belongs to my parent outside Calgary. What's needed?", "The registered owner signs in person or authorizes someone with the proper documents. Call first for the exact requirements."],
  ["How do you pay?", "Cash or e-transfer, before the vehicle leaves."],
] as const;

export default function CalgaryPage() {
  const schemas = [
    { "@context": "https://schema.org", "@type": "Service", "@id": "https://www.junkmycarreddeer.ca/cash-for-cars-calgary#service", name: "Cash for Cars Calgary", description: "Cash vehicle buying with free towing throughout Calgary.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-calgary", serviceType: "Cash vehicle buying and free vehicle removal", provider: { "@id": "https://www.junkmycarreddeer.ca/#business" }, areaServed: { "@type": "City", name: "Calgary", containedInPlace: { "@type": "AdministrativeArea", name: "Alberta" } } },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": "https://www.junkmycarreddeer.ca/cash-for-cars-calgary#faq", mainEntity: faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) },
  ];
  return <>
    <main className={styles.page}>
      <section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div className={styles.heroCopy}><nav><Link href="/">Home</Link><span>/</span><span>Cash for Cars Calgary</span></nav><p className={styles.kicker}>Calgary vehicle buyers</p><h1>Cash for Cars Calgary <span>— Sell Any Vehicle Without Listing It</span></h1><p>Running or not, paid off or not, Alberta plates or Ontario ones. Tell us what you&apos;re driving—or what you&apos;ve stopped driving—and we&apos;ll give you one firm number, collect it free from anywhere in Calgary, and pay you before it leaves.</p><div className={styles.actions}><a href="#calgary-quote">Get My Offer <ArrowRight /></a><a href={phoneHref}><Phone /> Call {phoneDisplay}</a></div><div className={styles.trust}><span>Buying vehicles in Alberta since 1998</span><span>AMVIC licensed</span><span>Free towing</span><span>Cash or e-transfer</span></div></div><div className={styles.heroImage}><Image src={heroPhoto} alt="Used SUV ready for a cash offer in Calgary" fill priority sizes="(max-width: 900px) 100vw, 46vw" /><div><MapPin /><strong>Free pickup across Calgary</strong><span>Same day or next day</span></div></div></div></section>
      <section id="calgary-quote" className={styles.quote}><div className="shell"><QuoteForm /></div></section>
      <section className={styles.answer}><div className="shell"><div className={styles.answerBox}><div><p className={styles.kicker}>The short answer</p><h2>Everything You Need to Know</h2></div><dl><div><dt>What we buy</dt><dd>Any car, truck, SUV or van—running, high-kilometre, damaged, written off or dead.</dd></div><div><dt>What you get</dt><dd>Typically $300 to $15,000+, quoted the same day, towing included.</dd></div><div><dt>How fast</dt><dd>Most Calgary pickups happen the same day or next day.</dd></div><div><dt>How you&apos;re paid</dt><dd>Cash or e-transfer before the vehicle moves.</dd></div><div><dt>What you need</dt><dd>Photo ID matching the registration and proof of ownership.</dd></div></dl></div></div></section>
      <section className={styles.section}><div className="shell"><header><p className={styles.kicker}>The obstacles first</p><h2>Why Selling a Car in Calgary Gets Complicated</h2><p>Calgary should make selling easy. Most people who call us already tried the obvious route and hit one of these walls.</p></header><div className={styles.painGrid}>{painPoints.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className={`${styles.section} ${styles.dark}`}><div className="shell"><header><p className={styles.kicker}>A real number</p><h2>What Your Car Is Worth</h2></header><div className={styles.valueGrid}><div className={styles.table}><div><strong>Vehicle situation</strong><strong>Typical offer</strong></div>{offers.map(([v,o]) => <div key={v}><span>{v}</span><strong>{o}</strong></div>)}</div><aside><BadgeDollarSign /><h3>What moves your number</h3><ul><li>Whether it runs and drives</li><li>Parts demand for the exact model</li><li>Completeness and the converter</li><li>Rust and structural damage</li></ul><p>The offer includes towing and stays firm unless the vehicle is materially different from its description.</p><a href="#calgary-quote">Get My Free Quote <ArrowRight /></a></aside></div></div></section>
      <section className={styles.section}><div className="shell"><header><p className={styles.kicker}>The honest comparison</p><h2>Trade-In, Private Sale or Cash Buyer?</h2><p>There is no single right answer. It depends on the car.</p></header><div className={styles.compare}><div><strong></strong><strong>Dealer trade-in</strong><strong>Private sale</strong><strong>Cash for cars</strong></div><div><strong>Best for</strong><span>Late-model, clean vehicles</span><span>Clean runners you can wait on</span><span>Older, damaged or hard-to-register vehicles</span></div><div><strong>Speed</strong><span>Same day, tied to purchase</span><span>Days to weeks</span><span>Same or next day</span></div><div><strong>Payment</strong><span>Purchase credit</span><span>Buyer&apos;s method</span><span>Cash or e-transfer</span></div><div><strong>Non-running?</strong><span>Rarely</span><span>Limited buyers</span><span>Yes</span></div><div><strong>Time and risk</strong><span>Low</span><span>High</span><span>Low</span></div></div><p className={styles.advice}><strong>Our advice:</strong> compare private-sale and trade figures on a clean vehicle under eight years old. If it is older, damaged, warning-lit, inspection-failed or dead, the cash route usually wins on time and often on money.</p></div></section>
      <section className={`${styles.section} ${styles.services}`}><div className="shell"><header><p className={styles.kicker}>Six ways we help</p><h2>Our Services in Calgary</h2><p>Every service is available citywide with free towing, a firm quote and payment before the vehicle leaves.</p></header><div className={styles.cards}>{services.map(([title, href, label, text], i) => <article key={title}><span>0{i + 1}</span>{i === 0 ? <BadgeDollarSign /> : i === 1 ? <Truck /> : i === 2 ? <ShieldCheck /> : i === 3 ? <Wrench /> : i === 4 ? <Car /> : <MapPin />}<h3>{title}</h3><p>{text}</p><Link href={href}>{label} <ArrowRight /></Link></article>)}</div></div></section>
      <section className={`${styles.section} ${styles.situations}`}><div className={`shell ${styles.split}`}><header><p className={styles.kicker}>Problem solved</p><h2>Calgary Situations We Solve Every Week</h2></header><div>{situations.map(([q,a],i) => <details key={q} open={i === 0}><summary>{q}<ChevronDown /></summary><p>{a}</p></details>)}</div></div></section>
      <section className={styles.safety}><div className={`shell ${styles.split}`}><div><p className={styles.kicker}>If you list it yourself</p><h2>Selling Privately? Protect Yourself First</h2><p>Or skip the listing and let us buy it. Either way, sell it safely.</p></div><ol><li>Confirm funds are in your bank—not a screenshot or email.</li><li>Never accept an overpayment and refund the difference.</li><li>Meet in daylight and never allow an unaccompanied test drive.</li><li>Complete and retain a proper signed bill of sale.</li><li>Keep your plate and update registration immediately.</li></ol></div></section>
      <section className={`${styles.section} ${styles.coverage}`}><div className="shell"><header><p className={styles.kicker}>Every quadrant</p><h2>Where We Collect in Calgary</h2></header><div className={styles.coverageGrid}><article><h3>North of the Bow</h3><p>Crescent Heights, Tuxedo Park, Huntington Hills, Harvest Hills, Panorama Hills, Coventry Hills, Hawkwood, Scenic Acres, Livingston, Carrington, Abbeydale, Penbrooke Meadows, Vista Heights, Cityscape and Savanna—plus Barlow Trail, McKnight Boulevard and airport-area industrial properties.</p></article><article><h3>South of the Bow</h3><p>Richmond, Lakeview, Currie Barracks, Haysboro, Kingsland, Canyon Meadows, Shawnessy, Somerset, Silverado, Midnapore, Sundance, Parkland, Lynnwood, Erin Woods, Quarry Park and Deer Ridge—plus Macleod Trail and 50th Avenue SE.</p></article><article><h3>Just outside the city</h3><p>Rocky View County and Foothills County properties along the city edge. Garages, lanes, underground stalls, shop lots, tow yards and long acreage approaches are all workable when described in advance.</p></article></div></div></section>
      <section className={styles.process}><div className="shell"><header><p className={styles.kicker}>Four simple steps</p><h2>How It Works</h2></header><div className={styles.steps}>{[["Tell us about it","Year, make, model, condition and location."],["Get a firm offer","Usually within hours, towing included."],["Choose a time","Same day or next, with a real window."],["Get paid","Paperwork, payment and loading in about twenty minutes."]].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div><p className={styles.note}><ClipboardCheck /> Before pickup, empty every compartment and remove parkade fobs, remotes and your licence plate.</p></div></section>
      <section className={styles.paperwork}><div className={`shell ${styles.split}`}><div><p className={styles.kicker}>Bring two things</p><h2>Alberta Paperwork for Calgary Sellers</h2></div><div><p>Bring photo ID matching the registered owner and proof of ownership, normally the registration certificate. We prepare the bill of sale on site.</p><p>Keep your Alberta plate, update registration at a Calgary registry and call your insurer about any prepaid-policy refund. Out-of-province, estate, company-owned and never-transferred vehicles are often workable after a short conversation.</p></div></div></section>
      <section className={styles.corridor}><div className="shell"><h2>Between Calgary and Red Deer</h2><p>Free pickup runs the full QEII corridor, including <Link href="/cash-for-cars-olds">Olds</Link>, <Link href="/cash-for-cars-bowden">Bowden</Link> and <Link href="/cash-for-cars-innisfail">Innisfail</Link>, with the same free towing and firm offers.</p></div></section>
      <section id="questions" className={`${styles.section} ${styles.faq}`}><div className={`shell ${styles.split}`}><header><p className={styles.kicker}>Straight answers</p><h2>Cash for Cars Calgary — Questions</h2></header><div>{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<ChevronDown /></summary><p>{a}</p></details>)}</div></div></section>
      <section className={styles.final}><div className={`shell ${styles.finalGrid}`}><div><p className={styles.kicker}>A firm number today</p><h2>Get Your Calgary Cash Offer Today</h2><p>Year, make, model and a quick description is all it takes.</p></div><div><a href={phoneHref}><Phone /> {phoneDisplay}</a><a href="#calgary-quote">Get a Free Offer <ArrowRight /></a></div></div></section>
    </main>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><Image src={logo} alt="Junk My Car Red Deer" sizes="230px" /><p>Firm cash offers and free vehicle towing throughout Calgary and the QEII corridor.</p><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div><div><h3>Services</h3><Link href="/junk-car-removal-red-deer">Junk Car Removal</Link><Link href="/scrap-car-removal-red-deer">Scrap Car Removal</Link><Link href="/sell-my-car-red-deer">Sell My Car</Link><Link href="/damaged-car-removal-red-deer">Damaged Cars</Link><Link href="/free-towing-red-deer">Free Towing</Link></div><div><h3>Company</h3><Link href="/about">About Us</Link><Link href="/how-it-works">How It Works</Link><Link href="/what-we-buy">What We Buy</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></div><div><h3>Get an offer</h3><p>Tell us the year, make, model and condition. We usually reply within a few hours.</p><a className="footer-quote" href="#calgary-quote">Request a quote <ArrowRight aria-hidden="true" /></a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Junk My Car Red Deer</span><span>Serving Calgary &amp; Central Alberta</span></div></footer>
    <BreadcrumbSchema current="Cash for Cars Calgary" path="/cash-for-cars-calgary" />
    {schemas.map((schema, index) => <JsonLd key={index} data={schema} />)}
  </>;
}
