import type { Metadata } from "next";
import heroPhoto from "@/assets/used-sedan-red-deer.jpeg";
import workPhoto from "@/assets/older-ford-f150-acreage.jpeg";
import { LocationPage } from "@/components/location-page";

export const metadata: Metadata = { title: "Cash for Cars Clive AB | Free Towing, Same-Day Cash", description: "Cash for cars Clive, Alberta. We buy shift-work commuters, non-runners, farm trucks, scrap and damaged vehicles, tow free, and pay at pickup.", alternates: { canonical: "https://www.junkmycarreddeer.ca/cash-for-cars-clive" }, openGraph: { title: "Cash for Cars Clive | Free Same-Day Towing", description: "Cash offers for shift-work commuters, farm trucks and non-runners throughout Clive and Lacombe County.", url: "https://www.junkmycarreddeer.ca/cash-for-cars-clive", type: "website", images: [{ url: heroPhoto.src, width: 1200, height: 630, alt: "High-kilometre commuter vehicle in Clive" }] } };
const data = {
  city: "Clive", path: "/cash-for-cars-clive", distance: "45 km", route: "Highway 12",
  heroTitle: "Cash for Cars Clive — Cash on Collection", heroText: "Thirty-five minutes from Red Deer on Highway 12. Any vehicle, any condition, village or county—free towing, one firm number and payment on the spot.",
  heroImage: heroPhoto, heroAlt: "High-kilometre commuter car purchased in Clive", secondaryImage: workPhoto, secondaryAlt: "Farm and work truck accepted near Clive",
  localTitle: "A Village That Runs on Shift Work", localIntro: "Plant rotations, extra household vehicles and surrounding farm country create a recognizable mix of high-kilometre commuters and working trucks.",
  localFactors: [{ title: "The plant commute", text: "Twelve-hour rotations to Joffre and Prentiss mean scheduled cold starts, rapid highway kilometres and five months of salt. Rocker and brake-line rust arrive before the vehicle's age suggests." }, { title: "The second shift-schedule vehicle", text: "Opposite rotations make sharing difficult, so households carry extra vehicles. When a schedule changes or someone retires, an insurance renewal often prompts the sale." }, { title: "Farm land all around", text: "Beyond the village, older trucks accumulate in Lacombe County yards. Several vehicles collected in one trip generally improve each offer." }],
  buyTypes: "Cars, SUVs, crossovers, half-tons, 3/4-tons, one-tons, diesel pickups, farm and work trucks, vans, commercial and fleet vehicles.", buyConditions: "No-starts, failed engines or transmissions, hail, collision, write-offs, fire, flood, rusted frames, failed inspections and partly stripped vehicles.",
  offers: [["Older car, complete, non-running", "$250 – $800"], ["High-kilometre commuter", "$800 – $3,500"], ["Half-ton, non-running, complete", "$600 – $1,800"], ["Farm or work truck, non-running", "$900 – $2,500"], ["Hail-damaged, mechanically sound", "$1,000 – $6,000"], ["Newer running truck, SUV or car", "$3,000 – $15,000"]] as const,
  valueText: "Weight establishes the floor, reusable components and catalytic converter content create the upside, and severe rust or missing parts reduce it. The quoted amount includes towing and remains firm when the description is accurate.",
  servicesIntro: "Built around shift rotations as much as vehicles—every service below can be booked around your schedule, covers Clive and surrounding Lacombe County, and includes free towing and payment on the spot.",
  services: [
    { title: "Junk Car Removal in Clive", before: "The car that finally failed on a four-a.m. cold start before a plant shift is a familiar Clive story. Our ", linkLabel: "junk car removal service", href: "/junk-car-removal-red-deer", after: " collects it as-is and books the pickup around your rotation, so you do not burn a day off dealing with a dead vehicle." },
    { title: "Scrap Car Removal in Clive", before: "Years of brine on the Highway 12 and 21 run to Joffre can rot rockers, brake lines and subframes past the point of a sensible repair. Our ", linkLabel: "scrap car removal", href: "/scrap-car-removal-red-deer", after: " pays on weight and metal, and handles the fluids properly before anything is recycled." },
    { title: "Sell My Car in Clive", before: "The extra vehicle a shift household ran for opposite rotations usually still drives—it is just not needed after a schedule change or retirement. Our ", linkLabel: "sell my car service", href: "/sell-my-car-red-deer", after: " turns it into one cash offer before the next insurance renewal." },
    { title: "Damaged and Write-Off Vehicles in Clive", before: "Dark early-morning commutes on rural highways mean deer strikes and winter collisions, and hail crosses the county most summers. Our ", linkLabel: "damaged car buying service", href: "/damaged-car-removal-red-deer", after: " buys salvage and non-repairable buybacks and prices the healthy drivetrain behind the damage." },
    { title: "Car Wreckers Serving Clive", before: "Older farm trucks from the yards around Clive and Tees still carry axles, transfer cases, boxes and tailgates that other operators want. As ", linkLabel: "car wreckers", href: "/car-wreckers-red-deer", after: " we recover those parts, which is why a complete truck gets more than a weight-only scrap quote." },
    { title: "Free Towing in Clive", before: "Thirty-five minutes on Highway 12, then out toward Joffre, Tees or Alix—no charge. ", linkLabel: "Free towing", href: "/free-towing-red-deer", after: " covers the village and surrounding farmland, including early or late pickups arranged around a rotation." },
  ],
  accessTitle: "Where We Collect", accessIntro: "Every Clive address plus farms and acreages toward Joffre, Tees and Alix are included.", accessItems: [{ title: "Village addresses", text: "Driveways, residential yards, rented stalls and shop lots throughout Clive." }, { title: "Lacombe County", text: "Highways 12 and 21 and the surrounding range roads, including farm yards and long gravel approaches." }, { title: "Shift-friendly scheduling", text: "Tell us your rotation. We can arrange practical pickup windows rather than asking you to take a day off." }],
  process: "Call or submit the year, make, model and condition. Offers return the same day and pickup is normally the same day or next. We provide a time window and can work around shift rotations.", paperwork: "We complete the bill of sale. Company, farm-corporation and estate vehicles are workable when the correct documents and signing authority are arranged before dispatch.",
  nearby: [["Lacombe", "20 km west"], ["Alix", "13 km east"], ["Blackfalds", "30 km southwest"], ["Stettler", "45 km east"], ["Lacombe County", "All rural properties"]] as const,
  faqs: [["I am on shift—can you come outside normal hours?", "Tell us your rotation and we will schedule around it."], ["My car has huge kilometres from the plant commute.", "That affects our number far less because we value weight and parts rather than remaining service life."], ["Is there any charge to come out?", "No mileage fee, minimum value or pickup deduction."], ["Two vehicles at the same address?", "One efficient trip normally improves each offer."], ["The underside is badly rusted.", "Common on this corridor. It lowers the amount but does not prevent a sale."], ["How long before you can get here?", "About thirty-five minutes. Same-day pickup is normal for morning calls."]] as const,
  finalTitle: "Get a Number",
};
export default function Page(){return <LocationPage data={data}/>;}
